title = {" Konveksni štirikotnik ima vse kote manjše od 180°.", 
         " Štirikotnik lahko ima vse ostre kote.",
         " Štirikotnik ima vsaj en kot manjši od 90°.",		 
         " Pravokotnik je paralelogram, katerega vsi koti so enaki.", 
		 " Če je eden od kotov paralelograma prav, je paralelogram pravokotnik.",
         " Kvadrat je pravokotnik, katerega vse stranice so enake in vsi koti enaki.",
         " Romb je paralelogram, katerega stranice so enake.", 		 
         " Romb je paralelogram, pri katerem so vsi koti enaki.", 	
         " Deltoid je štirikotnik, ki ima vse stranice enake.", 	
		 " Deltoid je štirikotnik, ki ima dva para enakih sosednjih stranic.",		 
         " Trapez je štirikotnik, ki ima en par enakih nasprotnih stranic.",
         " Trapez je štirikotnik, ki ima en par vzporednih nasprotnih stranic.",
         " Vsota notranjih kotov štirikotnika je 360°.",
         " Vsota zunanjih kotov štirikotnika je 360°.",	
         " Diagonala štirikotnika lahko meri manj kot najmanjša stranica štirikotnika.",
		 " Paralelogram je štirikotnik, ki ima dva para enakih nasprotnih kotov.",
		 " Diagonali paralelograma se razpolavljata.",
		 " Diagonali paralelograma sta enaki.",  		 
		 " Diagonali trapeza se razpolavljata.",	
		 " Diagonali enakokrakega trapeza sta enaki.",		 
		 " Diagonali deltoida sta pravokotni.",
         " Deltoid je štirikotnik, katerega nasprotna kota sta enaka.",
         " Deltoid je štirikotnik, ki ima en par enakih nasprotnih kotov."			 
		 } 

reply = {"t", "n", "n", "t", "t", "t", "t", "n", "n", "t", "n", "t", "t", "t", "n", "t", "t", "n", "n", "t", "t", "n", "t"}