title = {" Convex quadrilateral has all angles less than 180°.", 
         " Quadrilateral can have all acute angles.",
         " Quadrilateral has at least one angle less than 90°.",		 
         " Rectangle is a parallelogram with all angles equal.", 
		 " If one angle of a parallelogram is right, then the parallelogram is a rectangle.",
         " A square is a rectangle with all sides and angles equal.",
         " Rhombus is a parallelogram with all sides equal.", 		 
         " Rhombus is a parallelogram with all angles equal.", 	
         " A kite is a quadrilateral with two pairs of adjacent sides equal.", 	
		 " A kite is a quadrilateral with two adjacent sides equal.",		 
         " Trapezium is a quadrilateral with one pair of opposite sides equal.",
         " Trapezium is a quadrilateral with one pair of parallel opposite sides.",
         " The sum of the interior angles of a quadrilateral is 360°.",
         " The sum of the exterior angles of a quadrilateral is 360°.",	
         " The diagonal of a quadrilateral can be shorter than the shortest side of the quadrilateral.",
		 " A parallelogram is a quadrilateral with two pairs of opposite equal angles.",
		 " The diagonals of a parallelogram bisect each other.",
		 " The diagonals of a parallelogram are equal.",  		 
		 " The diagonals of a trapezium bisect each other.",	
		 " The diagonals of an isosceles trapezium are equal.",		 
		 " The diagonals of a kite are perpendicular.",
         " A kite is a quadrilateral with opposite angles equal.",
         " A kite is a quadrilateral with one pair of opposite equal angles."			 
		 } 

reply = {"t", "n", "n", "t", "t", "t", "t", "n", "n", "t", "n", "t", "t", "t", "n", "t", "t", "n", "n", "t", "t", "n", "t"}