title = {"Paralelogram je središčno simetričen lik.",
         "Središče simetrije paralelograma je presečišče diagonal.",
         "Enakokraki trapez je sredinsko simetričen lik.",
         "Deltoid je središčno simetričen lik.",
         "Paralelogram je osno simetričen lik.",
         "Pravokotnik je osno simetričen lik.",
         "Romb je osno simetričen lik.",
         "Trapez je osno simetričen lik.",
         "Enakokraki trapez je osno simetričen lik.",
         "Deltoid je osno simetričen lik.",
         "Dijagonale pravokotnika so simetrale ustreznih kotov.",
         "Dijagonale romba so simetrale ustreznih kotov.",
         "V romb se lahko včrta krog.", 
         "Okoli romba se lahko očrta krog.",
		 "Dijagonala romba je premer očrtanega kroga.",  
         "Višina romba je premer včrtanega kroga.",
         "Paralelogram včrtan v krog je pravokotnik.",
         "Dijagonala pravokotnika je premer očrtanega kroga.",
         "Paralelogram ima štiri osi simetrije.",
         "Pravokotnik ima štiri osi simetrije.",
         "Pravokotnik ima dve osi simetrije.",		 
         "Dijagonale trapeza delijo na dva enaka dela ustrezne kote.",
         "Dijagonale deltoida delijo na dva enaka dela nasprotne kote, ki niso enaki."
         }

reply = {"t", "t", "n", "n", "n", "t", "t", "n", "t", "t", "n", "t", "t", "n", "n", "t", "t", "t", "n", "n", "t", "n", "t"}