text = {"Sphere is a round body.",
		"Sphere is a round surface.", 	
		"Ball is a rotating body.",        		
		"Ball is a round body.", 
        "Ball is a round surface.", 
        "Ball is a round body bounded by a sphere.", 		
        "All points of a sphere are equidistant from its center.", 		
        "The radius of a sphere is the distance of any point on the sphere from its center.", 
		"A point is inside a sphere if its distance from the center is greater than the radius.",
		"A point is inside a sphere if its distance from the center is less than the radius.",	
        "All points of a ball are equidistant from its center.", 		
        "The distance of any point on the ball from its center is at most equal to the ball's radius.", 
        "The distance of any point on a sphere from its center is at most equal to the sphere's radius.", 
		"Ball is the surface of a sphere.", 
		"Sphere is the surface of a ball.",
		"A plane section is the intersection of a ball and a plane.",
		"If a plane and a sphere intersect, their intersection is a circle.",		
		"If a plane and a sphere intersect, their intersection is a circle.",
		"If a plane and a ball intersect, their intersection is a circle.",		
		"If a plane and a ball intersect, their intersection is a circle.",		
		"The great circle of a ball is the intersection of the ball and a plane containing the center of the ball.",
		"The great circle of a ball is the intersection of the ball and a plane.",
		"The radius of the great circle is the radius of the ball.",
		"The center of the great circle is the center of the ball.",
		"The circumference of the ball is the circumference of the great circle.",		
		"A spherical belt is a part of a sphere cut by a secant plane.",	
		"A spherical belt is a part of a sphere between two parallel secant planes.",
		"A spherical cap is a part of a sphere cut by a secant plane.",	
		"A spherical cap is a part of a sphere between two parallel secant planes.",	
		"A hemisphere is a cap cut by a great circle.",	
		"A cap is a part of a ball cut by a secant plane.",	
		"A segment of a ball is a part of a ball bounded by a cap and a secant plane.",
		"A hemisphere is a segment of a ball cut by a great circle.",	
		"A hemisphere is a cap cut by a great circle.",	
		"A segment of a ball is a part of a ball bounded by a cap and a secant plane.",	
		"A tangent plane has one common point with the ball.",
		"A tangent plane contains the center of the ball.",	
		"Of all bodies of equal surface area, a ball has the largest volume.",
		"Of all bodies of equal volume, a ball has the largest surface area.",	
		"A ball is formed by rotating a circle around its diameter." }		

reply = {"n", "t", "t", "t", "n", "t", "t", "t", "n", "t",
         "n", "t", "n", "n", "t", "t", "t", "n", "n", "t", 
         "t", "n", "t", "t", "t", "n", "t", "t", "n", "t",
         "n", "t", "n", "n", "t", "t", "n", "t", "n", "t" }