text = {"Sfera je okroglo telo.",
		"Sfera je okrogla ploskev.", 	
		"Krogla je vrtenina.",        		
		"Krogla je okroglo telo.", 
        "Krogla je okrogla ploskev.", 
        "Krogla je okroglo telo, ki ga omejuje sfera.", 		
        "Vse točke sfere so enako oddaljene od njenega centra.", 		
        "Polmer sfere je razdalja katerekoli točke sfere od njenega centra.", 
		"Točka je v sferi, če je njena razdalja od centra večja od polmera.",
		"Točka je v sferi, če je njena razdalja od centra manjša od polmera.",	
        "Vse točke krogle so enako oddaljene od njenega centra.", 		
        "Razdalja katerekoli točke krogle od njenega centra je največ enaka polmeru lopte.", 
        "Razdalja katerekoli točke sfere od njenega centra je največ enaka polmeru sfere.", 
		"Krogla je ploskev sfere.", 
		"Sfera je ploskev krogle.",
		"Ravni presek je presek krogle in ravnine.",
		"Če se ravnina in sfera sekata, njun presek je krožnica.",		
		"Če se ravnina in sfera sekata, njun presek je krog.",
		"Če se ravnina in krogla sekata, njun presek je krožnica.",		
		"Če se ravnina in krogla sekata, njun presek je krog.",		
		"Veliki krog krogle je presek krogle in ravnine, ki vsebuje center krogle.",
		"Veliki krog krogle je presek krogle in ravnine.",
		"Polmer velikega kroga je polmer krogle.",
		"Center velikega kroga je center krogle.",
		"Obseg krogle je obseg velikega kroga.",		
		"Sferični pas je del sfere, ki ga odreže sekalna ravnina.",	
		"Sferični pas je del sfere med dvema vzporednima sekalnim ravninama.",
		"Kalota je del sfere, ki ga odreže sekalna ravnina.",	
		"Kalota je del sfere med dvema vzporednima sekalnim ravninama.",	
		"Polusfera je kalota, ki jo odreže veliki krog.",	
		"Kalota je del krogle, ki ga odreže sekalna ravnina.",	
		"Kroglin odrezek je del krogle, omejen s kalotom in sekalno ravnino.",
		"Polusfera je kroglin odrezek, ki ga odreže veliki krog.",	
		"Polukrogla je kalota, ki jo odreže veliki krog.",	
		"Polulopta je loptin odrezek, ki ga odreže veliki krog.",	
		"Tangentna ravnina ima s kroglo eno skupno točko.",
		"Tangentna ravnina vsebuje center krogle.",	
		"Iz vseh teles enake površine krogla ima največju prostorninu.",
		"Iz vseh teles enake prostornine krogla ima največjo površino.",	
		"Krogla nastane z vrtenjem kroga okoli premera." }		

reply = {"n", "t", "t", "t", "n", "t", "t", "t", "n", "t",
         "n", "t", "n", "n", "t", "t", "t", "n", "n", "t", 
         "t", "n", "t", "t", "t", "n", "t", "t", "n", "t",
         "n", "t", "n", "n", "t", "t", "n", "t", "n", "t" }
