text = {"Sfera je oblo telo.",
		"Sfera je obla površ.", 	
		"Lopta je obrtno telo.",        		
		"Lopta je oblo telo.", 
        "Lopta je obla površ.", 
        "Lopta je oblo telo ograničeno sferom.", 		
        "Sve tačke sfere su jednako udaljene od njenog centra.", 		
        "Poluprečnik sfere je rastojanje bilo koje tačke sfere od njenog centra.", 
		"Tačka je u sferi ako je njeno rastojanje od centra veće od poluprečnika.",
		"Tačka je u sferi ako je njeno rastojanje od centra manje od poluprečnika.",	
        "Sve tačke lopte su jednako udaljene od njenog centra.", 		
        "Rastojanje bilo koje tačke lopte od njenog centra je najviše jednako poluprečniku lopte.", 
        "Rastojanje bilo koje tačke sfere od njenog centra je najviše jednako poluprečniku sfere.", 
		"Lopta je površ sfere.", 
		"Sfera je površ lopte.",
		"Ravni presek je presek lopte i ravni.",
		"Ako se ravan i sfera seku, njihov presek je kružnica.",		
		"Ako se ravan i sfera seku, njihov presek je krug.",
		"Ako se ravan i lopta seku, njihov presek je kružnica.",		
		"Ako se ravan i lopta seku, njihov presek je krug.",		
		"Veliki krug lopte je presek lopte i ravni koja sadrži centar lopte.",
		"Veliki krug lopte je presek lopte i ravni.",
		"Poluprečnik velikog kruga je poluprečnik lopte.",
		"Centar velikog kruga je centar lopte.",
		"Obim lopte je obim velikog kruga.",		
		"Sferni pojas je deo sfere koji odseca presečna ravan.",	
		"Sferni pojas je deo sfere između dve paralelne presečne ravani.",
		"Kalota je deo sfere koji odseca presečna ravan.",	
		"Kalota je deo sfere između dve paralelne presečne ravani.",	
		"Polusfera je kalota koju odseca veliki krug.",	
		"Kalota je deo lopte koji odseca presečna ravan.",	
		"Loptin odsečak je deo lopte ograničen kalotom i presečnom ravni.",
		"Polusfera je loptin odsečak koji odseca veliki krug.",	
		"Polulopta je kalota koju odseca veliki krug.",	
		"Polulopta je loptin odsečak koji odseca veliki krug.",	
		"Tangentna ravan ima sa loptom jednu zajedničku tačku.",
		"Tangentna ravan sadrži centar lopte.",	
		"Od svih tela jednake površine najveću zapreminu ima lopta.",
		"Od svih tela jednake zapremine najveću površinu ima lopta.",	
		"Lopta nastaje rotacijom kruga oko prečnika." }		

reply = {"n", "t", "t", "t", "n", "t", "t", "t", "n", "t",
         "n", "t", "n", "n", "t", "t", "t", "n", "n", "t", 
         "t", "n", "t", "t", "t", "n", "t", "t", "n", "t",
         "n", "t", "n", "n", "t", "t", "n", "t", "n", "t" }
