text = {"A sphere is a round body.",
		"A sphere is a round surface.", 	
		"A ball is a rotating body.",        		
		"A ball is a round body.", 
        "A ball is a round surface.", 
        "A ball is a round body bounded by a sphere.", 		
        "All points of the sphere are equidistant from its center.", 		
        "The radius of a sphere is the distance of any point on the sphere from its center.", 
		"A point is inside a sphere if its distance from the center is greater than the radius.",
		"A point is inside a sphere if its distance from the center is less than the radius.",	
        "All points of the ball are equidistant from its center.", 		
        "The distance of any point of the ball from its center is at most equal to the ball's radius.", 
        "The distance of any point of a sphere from its center is at most equal to the sphere's radius.", 
		"A ball is the surface of a sphere.", 
		"A sphere is the surface of a ball.",
		"A cross-section is the intersection of a ball and a plane.",
		"If a plane and a sphere intersect, their intersection is a circle line.",		
		"If a plane and a sphere intersect, their intersection is a circle.",
		"If a plane and a ball intersect, their intersection is a circle-line.",		
		"If a plane and a ball intersect, their intersection is a circle.",		
		"A great circle of a ball is the cross-section of the ball and a plane containing the center of the ball.",
		"A great circle of a ball is the cross-section of the ball and a plane.",
		"The radius of the great circle is the radius of the ball.",
		"The center of the great circle is the center of the ball.",
		"The circumference of the ball is the circumference of the great circle.",		
		"A spherical belt is a part of a sphere cut by a secant plane.",	
		"A spherical belt is a part of a sphere between two parallel secant planes.",
		"A calotte is a part of a sphere cut by a secant plane.",	
		"A calotte is a part of a sphere between two parallel secant planes.",	
		"A hemisphere is a calotte cut by a great circle.",	
		"A calotte is a part of a ball cut by a secant plane.",	
		"A ball segment is a part of a ball bounded by a calotte and a secant plane.",
		"A hemisphere is a segment of a ball cut by a great circle.",	
		"A halfball is a calotte cut off by a great circle.",	
		"A halfball is a part of a ball cut off by a great circle.",	
		"A tangent plane has one common point with the ball.",
		"A tangent plane contains the center of the ball.",	
		"Among all bodies of equal surface area, a ball has the largest volume.",
		"Among all bodies of equal volume, a ball has the largest surface area.",	
		"A ball is formed by rotating a circle around its diameter." }		

reply = {"n", "t", "t", "t", "n", "t", "t", "t", "n", "t",
         "n", "t", "n", "n", "t", "t", "t", "n", "n", "t", 
         "t", "n", "t", "t", "t", "n", "t", "t", "n", "t",
         "n", "t", "n", "n", "t", "t", "n", "t", "n", "t" }