text = {"Sfera je oblo telo.",
		"Sfera je obla površ.", 	
		"Lopta je obrtno telo.",        		
		"Lopta je oblo telo.", 
        "Lopta je obla površ.", 
        "Lopta je oblo telo ograničeno sferom.", 		
        "Vse točke sfere so enako oddaljene od njenega centra.", 		
        "Polmer sfere je razdalja katerekoli točke sfere od njenega centra.", 
		"Točka je v sferi, če je njena razdalja od centra večja od polmera.",
		"Točka je v sferi, če je njena razdalja od centra manjša od polmera.",	
        "Vse točke lopte so enako oddaljene od njenega centra.", 		
        "Razdalja katerekoli točke lopte od njenega centra je največ enaka polmeru lopte.", 
        "Razdalja katerekoli točke sfere od njenega centra je največ enaka polmeru sfere.", 
		"Lopta je površ sfere.", 
		"Sfera je površ lopte.",
		"Ravni presek je presek lopte in ravni.",
		"Če se ravnina in sfera sekata, njun presek je krožnica.",		
		"Če se ravnina in sfera sekata, njun presek je krog.",
		"Če se ravnina in lopta sekata, njun presek je krožnica.",		
		"Če se ravnina in lopta sekata, njun presek je krog.",		
		"Veliki krog lopte je presek lopte in ravnine, ki vsebuje center lopte.",
		"Veliki krog lopte je presek lopte in ravnine.",
		"Polmer velikega kroga je polmer lopte.",
		"Center velikega kroga je center lopte.",
		"Obseg lopte je obseg velikega kroga.",		
		"Sferni pas je del sfere, ki ga odreže presečna ravnina.",	
		"Sferni pas je del sfere med dvema vzporednima presečnima ravnima.",
		"Sferna polkrožnica je del sfere, ki ga odreže presečna ravnina.",	
		"Sferna polkrožnica je del sfere med dvema vzporednima presečnima ravnima.",	
		"Polusfera je polkrožnica, ki jo odreže veliki krog.",	
		"Polkrožnica je del lopte, ki ga odreže presečna ravnina.",	
		"Loptin odrezek je del lopte, omejen s polkrožnico in presečno ravnino.",
		"Polusfera je loptin odrezek, ki ga odreže veliki krog.",	
		"Polulopta je polkrožnica, ki jo odreže veliki krog.",	
		"Polulopta je loptin odrezek, ki ga odreže veliki krog.",	
		"Tangentna ravnina ima s kroglo eno skupno točko.",
		"Tangentna ravnina vsebuje center lopte.",	
		"Iz vseh teles enake površine ima največji volumen krogla.",
		"Iz vseh teles enakega volumna ima največjo površino krogla.",	
		"Lopta nastane z vrtenjem kroga okoli premera." }		

reply = {"n", "t", "t", "t", "n", "t", "t", "t", "n", "t",
         "n", "t", "n", "n", "t", "t", "t", "n", "n", "t", 
         "t", "n", "t", "t", "t", "n", "t", "t", "n", "t",
         "n", "t", "n", "n", "t", "t", "n", "t", "n", "t" }