text = {"Cylinder is a rounded body.",
		"Cylinder is a horned body.", 	
		"Cylinder is a rotating body.",        		
		"A straight line that rotates around a circle and contains a given point outside the circle plane describes a conical surface.", 		
        "A conical surface is a plane.", 
        "The vertex of the conical surface is the center of rotation of the straight line that describes the conical surface.", 		
        "A cylinder or cone is a body bounded by a circle and part of the conical surface between the circle and the vertex.", 		
        "The axis is a straight line that contains the center of the circle and the vertex of the conical surface.", 
        "A generatrix is a straight line that, by its rotation around the axis, describes a conical surface.",   		
        "The axis of a cylinder is perpendicular to the plane of the circle.",		
        "The generatrix and axis of the conical surface are parallel lines.", 
        "The generatrix and axis of the conical surface are non-intersecting lines.", 		
        "The generatrix and axis of the conical surface are mutually perpendicular lines.", 		
        "The generatrix and axis of the conical surface are intersecting lines.",			
        "The envelope of a cylinder is a triangle.",		
        "The envelope of a cylinder is a part of the conical surface.",		
        "The base of a cylinder is a polygon.",
        "The base of a cylinder is a circle.",				
		"The height of a cylinder is a segment of the axis of the conical surface.",		
		"The height of a cylinder is a segment of the generatrix of the conical surface.",			
		"The height of a cylinder is a line segment whose endpoints are the center of the base circle and the vertex of the cylinder.",			
		"The generatrix of a cylinder is a line that connects the vertex to a point on the circular line of the base of the cylinder.",		
		"The cross-section of a cylinder is a circle congruent to the base.",
		"The cross-section of a cylinder is a circle.",		
 		"The cross-section of a cylinder is a triangle.",		
		"The axial section of a cylinder is a circle.",		
 		"The axial section of a cylinder is a triangle.",		
		"The axial section of a cylinder is a normal section containing the axis.",		
		"A cylinder is equilateral if its axial section is an equilateral triangle.",		
		"The axial section of any cylinder is an equilateral triangle.",			
	    "The height of an equilateral cylinder is equal to the diameter of the base.", 		
	    "The height of an equilateral cylinder is equal to the radius of the base.",			
	    "The cylinder is formed by rotating a right-angled triangle around either cathetus.", 
	    "The cylinder is formed by rotating a right-angled triangle around the hypotenuse.",		
		"In a cylinder, the base of the height is the center of the base.",
		"The generatrix of a cylinder is greater than the radius of the base.",
		"The generatrix of a cylinder can be smaller than the radius of the base."}		

reply = {"t", "n", "t", "t", "n", "t", "t", "t", "t", "t", "n", "n", "n", "t", "n", "t", "n", "t", "t", "n", "t", "t", "n", "t", "n", "n", "t", "t", "t", "n", "n", "n", "t", "n", "t", "t","n"}