
text = {"Kupa je oblo telo.",
		"Kupa je rogljasto telo.", 	
		"Kupa je obrtno telo.",        		
		"Prava koja rotira oko kruga i sadrži datu tačku van ravni kruga opisuje konusnu površ .", 		
        "Konusna površ je ravan.", 
        "Vrh konusne površi je centar rotacije prave koja opisuje konusnu površ.", 		
        "Kupa ili konus je telo ograničeno krugom i delom konusne površi između kruga i vrha.", 		
        "Osa je prava koja sadrži centar kruga i vrh konusne površi.", 
        "Izvodnica je prava koja svojim obrtanjem oko ose opisuje konusnu površ.",   		
        "Osa prave kupe je normalna na ravan kruga.",		
        "Izvodnica i osa konusne površi su paralelne prave.", 
        "Izvodnica i osa konusne površi su mimoilazne prave.", 		
        "Izvodnica i osa konusne površi su uzajamno normalne prave.", 		
        "Izvodnica i osa konusne površi su prave koje se seku.",			
        "Omotač kupe je trougao.",		
        "Omotač kupe je deo konusne površi.",		
        "Osnova ili baza kupe je mnogougao.",
        "Osnova ili baza kupe je krug.",				
		"Visina prave kupe je odsečak ose konusne površi.",		
		"Visina prave kupe je odsečak izvodnice konusne površi.",			
		"Visina prave kupe je duž čiji su krajevi centar kruga osnove  i vrh kupe.",			
		"Izvodnica kupe je duž koja spaja vrh sa nekom tačkom na kružnoj liniji osnove kupe.",		
		"Paraleni presek kupe je krug podudaran osnovi.",
		"Paraleni presek kupe je krug.",		
 		"Paraleni presek kupe je trougao.",		
		"Osni presek kupe je krug.",		
 		"Osni presek kupe je trougao.",		
		"Osni presek kupe je normalni presek koji sadrži osu.",		
		"Kupa je ravnostrana ako joj je osni presek jednakostranični trougao.",		
		"Osni presek svake prave kupe je jednakostranični trougao.",			
	    "Visina ravnostrane kupe jednaka je prečniku osnove.", 		
	    "Visina ravnostrane kupe jednaka je poluprečniku osnove.",			
	    "Prava kupa nastaje obrtanjem pravouglog trougla oko bilo koje katete.", 
	    "Prava kupa nastaje obrtanjem pravouglog trougla oko hipotenuze.",		
		"Kod prave kupe podnožje visine je centar osnove.",
		"Izvodnica prave kupe veća je od poluprečnika osnove.",
		"Izvodnica prave kupe može biti manja od poluprečnika osnove."}		

reply = {"t", "n", "t", "t", "n", "t", "t", "t", "t", "t", "n", "n", "n", "t", "n", "t", "n", "t", "t", "n", "t", "t", "n", "t", "n", "n", "t", "t", "t", "n", "n", "n", "t", "n", "t", "t","n"}
