text = {"Stožec je okroglo telo.",
		"Stožec je rogasto telo.", 	
		"Stožec je vrtenina.",        		
		"Premica, ki se vrti okoli kroga in vsebuje dano točko izven ravnine kroga, tvori stožčasto ploskev.", 		
        "Stožčasta ploskev je ravnina.", 
        "Vrh stožčaste ploskve je središče vrtenja premice, ki tvori stožčasto ploskev.", 		
        "Stožec je telo, omejeno s krogom in delom stožčaste ploskve med krogom in vrhom.", 		
        "Os je premica, ki vsebuje središče kroga in vrh stožčaste ploskve.", 
        "Izvodnica je premica, ki z vrtenjem okoli osi tvori stožčasto ploskev.",   		
        "Os pokončnega stožca je pravokotna na ravnino kroga.",		
        "Izvodnica in os stožčaste ploskve sta vzporedni premici.", 
        "Izvodnica in os stožčaste ploskve sta mimoidoči premici.", 		
        "Izvodnica in os stožčaste ploskve sta medsebojno pravokotni premici.", 		
        "Izvodnica in os stožčaste ploskve sta sekajoči se premici.",			
        "Plašč stožca je trikotnik.",		
        "Plašč stožca je del stožčaste ploskve.",		
        "Osnovna ploskev stožca je mnogokotnik.",
        "Osnovna ploskev stožca je krog.",				
		"Višina pokončnega stožca je odsek osi stožčaste ploskve.",		
		"Višina pokončnega stožca je odsek izvodnice stožčaste ploskve.",			
		"Višina pokončnega stožca je daljica katere kraji so središče kroga osnovne ploskve in vrh stožca.",			
		"Izvodnica stožca je premica, ki povezuje vrh s točko na krožnici osnovne ploskve stožca.",		
		"Vzporedni presek stožca je krog, ki je skladen z osnovno ploskev.",
		"Vzporedni presek stožca je krog.",		
 		"Vzporedni presek stožca je trikotnik.",		
		"Osni presek stožca je krog.",		
 		"Osni presek stožca je trikotnik.",		
		"Osni presek stožca je pravokotni presek, ki vsebuje os.",		
		"Stožac je enakostranični če je njegov osni presek enakostranični trikotnik.",		
		"Osni presek vsakega pokončnega stožca je enakostranični trikotnik.",			
	    "Višina enakostraničnega stožca je enaka premeru osnove.", 		
	    "Višina enakostraničnega stožca je enaka polmeru osnove.",			
	    "Pokončni stožac nastane z vrtenjem pravokotnega trikotnika okoli poljubnega kraka.", 
	    "Pokončni stožac nastane z vrtenjem pravokotnega trikotnika okoli hipotenuze.",		
		"Kod pokončnega stožca projekcija višine je središče kroga osnovne ploskve.",
		"Izvodnica pokončnega stožca je večja od polmera osnove.",
		"Izvodnica pokončnega stožca je lahko manjša od polmera osnove."}		

reply = {"t", "n", "t", "t", "n", "t", "t", "t", "t", "t", "n", "n", "n", "t", "n", "t", "n", "t", "t", "n", "t", "t", "n", "t", "n", "n", "t", "t", "t", "n", "n", "n", "t", "n", "t", "t","n"}