text = {"A cone is a round body.",
		"A cone is a horned body.", 	
		"A cone is a vortex body.",        		
		"A straight line that rotates around a circle and contains a given point outside the plane of the circle creates a conical surface.", 		
        "A conical surface is a plane.", 
        "The apex of the conical surface is the center of rotation of the line creating the conical surface.", 		
        "A cone is a body bounded by a circle and part of the conical surface between the circle and the apex.", 		
        "The axis is a straight line that contains the center of the circle and the apex of the conical surface.", 
        "A generatrix is a straight line that, by its rotation around the axis, creates a conical surface.",   		
        "The axis of a right cone is perpendicular to the plane of the circle.",		
        "The generatrix and axis of the conical surface are parallel lines.", 
        "The generatrix and axis of the conical surface are skew lines.", 		
        "The generatrix and axis of the conical surface are mutually perpendicular lines.", 		
        "The generatrix and axis of the conical surface are intersecting lines.",			
        "The envelope of a cone is a triangle.",		
        "The envelope of a cone is a part of the conical surface.",		
        "The base of a cone is a polygon.",
        "The base of a cone is a circle.",				
		"The height of a right cone is a segment of the axis of the conical surface.",		
		"The height of a right cone is a segment of the generatrix of the conical surface.",			
		"The height of a right cone is a line segment whose endpoints are the center of the base circle and the apex of the cone.",			
		"The generatrix of a cone is a line that connects the apex to a point on the circular line of the cone base.",		
		"The parallel cross-section of a cone is a circle congruent to the base.",
		"The parallel cross-section of a cone is a circle.",		
 		"The parallel cross-section of a cone is a triangle.",		
		"The axial cross-section of a cone is a circle.",		
 		"The axial cross-section of a cone is a triangle.",		
		"The axial cross-section of a cone is a perpendicular section containing the axis.",		
		"A cone is equilateral if its axial cross-section is an equilateral triangle.",		
		"The axial cross-section of any right cone is an equilateral triangle.",			
	    "The height of an equilateral cone is equal to the diameter of the base.", 		
	    "The height of an equilateral cone is equal to the radius of the base.",			
	    "The right cone is formed by rotating a right-angled triangle around either cathetus.", 
	    "The right cone is formed by rotating a right-angled triangle around the hypotenuse.",		
		"In a right cone, the projection of the height is the center of the base.",
		"The generatrix of a right cone is greater than the radius of the base.",
		"The generatrix of a right cone can be smaller than the radius of the base."}		

reply = {"t", "n", "t", "t", "n", "t", "t", "t", "t", "t", "n", "n", "n", "t", "n", "t", "n", "t", "t", "n", "t", "t", "n", "t", "n", "n", "t", "t", "t", "n", "n", "n", "t", "n", "t", "t","n"}