text = {"Pyramid is a polyhedron with two parallel congruent polygons.",
		"Pyramid is a solid whose one side is a polygon, and the other sides are triangles with a common vertex.",
        "The base of the pyramid is a polygon.",
        "The base of the pyramid is always a triangle.",
        "The lateral faces of the pyramid form parallelograms.",
        "The lateral faces of the pyramid form triangles.",
        "The apex of the pyramid is a common point of all lateral faces.",
        "The apex of the pyramid is a common point of all lateral edges.",
        "Tetrahedron is a four-sided pyramid.",
        "Tetrahedron is a three-sided pyramid.",
        "The height of the pyramid is the length perpendicular to the base plane, with its ends being the apex of the pyramid and its projection on the base plane.",
        "The name of the pyramid is determined by the type of polygon representing the base.",
        "The height of the pyramid is the distance from the apex to the base plane of the pyramid.",
        "The height of the pyramid is the shortest lateral edge of the pyramid.",
        "The pyramid is right if the base of the pyramid is the center of the circle circumscribed around the base.",
        "The pyramid is right if one lateral edge is perpendicular to the base plane.",
        "The pyramid is right if a circle can be circumscribed around its base.",
        "The lateral edges of the right pyramid are equal to each other.",
        "The pyramid is right only if its base is a regular polygon.",
        "The lateral faces of the right pyramid consist exclusively of equilateral triangles.",
        "The lateral faces of the right pyramid consist exclusively of isosceles or equilateral triangles.",
        "The pyramid is regular if its base is a regular polygon.",
        "Regular tetrahedron is a solid with four congruent equilateral triangles as sides.",
        "The main diagonal section of a regular pyramid is an isosceles triangle determined by two non-adjacent lateral edges and contains the height.",
        "A regular triangular pyramid does not have a diagonal section.",
        "A regular triangular pyramid has three diagonal sections.",
        "The diagonal section of a regular pyramid is an isosceles triangle.",
        "The diagonal section of a regular pyramid is always an equilateral triangle.",
        "The pyramid has an odd number of edges.",
        "An obtuse-angled triangle cannot be the base of a right pyramid.",
        "Any triangle can be the base of a right pyramid.",
        "A rhombus can be the base of a right pyramid.",
        "The pyramid is right if all its lateral edges are equal.",
        "The base of the height of the right pyramid is always located inside the base."}		

reply = {"n", "t", "t", "n", "n", "t", "t", "t", "n", "t", "t", "t", "t", "n", "t", "n", "н", "t", "n", "n", "t", "t", "t", "t", "t", "n", "t", "n", "n", "n", "t", "n", "t", "n"}