text = {"Piramida je poliedar s štirimi vzporednimi enakokraki mnogokotniki.",
		"Piramida je telo, katere ena stran je mnogokotnik, ostale strani pa so trikotniki s skupno točko.",
		"Osnova piramide je mnogokotnik.",
		"Osnova piramide je vedno trikotnik.",
		"Ovojnica piramide tvorijo paralelogrami.",
		"Ovojnica piramide tvorijo trikotniki.",
		"Vrh piramide je skupna točka vseh stranic.",
		"Vrh piramide je skupna točka vseh bočnih robov.",
		"Tetraedar je štiristrana piramida.",
		"Tetraedar je trikotna piramida.",
		"Višina piramide je daljica, ki stoji pravokotno na ravnino osnove, katerih konci so vrh piramide in njena projekcija na ravnino osnove.",
		"Ime piramide je določeno s tipom mnogokotnika, ki predstavlja osnovo.",
		"Višina piramide je razdalja vrha od ravnine osnove piramide.",
		"Višina piramide je najkrajši bočni rob piramide.",
		"Piramida je pravilna, če je osnova visine piramide središče krožnice, ki opiše osnovo.",
		"Piramida je pravilna, če je en bočni rob pravokoten na ravnino osnove.",
		"Piramida je pravilna, če se okoli njene osnove lahko opiše krožnica.",
		"Bočni robovi prave piramide so enaki med seboj.",
		"Piramida je pravilna le, če je njena osnova pravilni mnogokotnik.",
		"Ovojnica prave piramide sestavljajo izključno enakostranični trikotniki.",
		"Ovojnica prave piramide sestavljajo izključno enakostranični ali enakostranični trikotniki.",
		"Piramida je pravilna, če je njena osnova pravilni mnogokotnik.",
		"Pravilni tetraedar je telo, katerega stranice so štirje enakokraki trikotniki.",
		"Glavni diagonalni prerezi pravilne piramide so enakostranični trikotnik, določen z dvema nesosednjima bočnima robovoma in vsebuje višino.",
		"Pravilna trikotna piramida nima diagonalnega prereza.",
		"Pravilna trikotna piramida ima tri diagonalne preseke.",
		"Diagonalni presek pravilne piramide je enakostranični trikotnik.",
		"Diagonalni presek pravilne piramide je vedno enakostranični trikotnik.",
		"Piramida ima liho število robov.",
		"Tupokotni trikotnik ne more biti osnova prave piramide.",
		"Vsak trikotnik lahko služi kot osnova prave piramide.",
		"Romb lahko služi kot osnova prave piramide.",
		"Piramida je pravilna, če so vse njene bočne robove enake.",
		"Osnova višine prave piramide je vedno znotraj osnove."
		}

reply = {"n", "t", "t", "n", "n", "t", "t", "t", "n", "t", "t", "t", "t", "n", "t", "n", "н", "t", "n", "n", "t", "t", "t", "t", "t", "n", "t", "n", "n", "n", "t", "n", "t", "n"}