text = {"Piramida je polieder z dvema vzporednima skladnima mnogokotnikoma.",
		"Piramida je telo, katere ena stran je mnogokotnik, ostale strani pa so trikotniki s skupno točko.",
		"Osnovna ploskev piramide je mnogokotnik.",
		"Osnovna ploskev piramide je vedno trikotnik.",
		"Plašč piramide tvorijo paralelogrami.",
		"Plašč piramide tvorijo trikotniki.",
		"Vrh piramide je skupna točka vseh stranskih ploskev.",
		"Vrh piramide je skupna točka vseh stranskih robov.",
		"Tetraedar je štiristranska piramida.",
		"Tetraedar je tristranska piramida.",
		"Višina piramide je daljica, ki stoji pravokotno na osnovno ploskev, katerih konci so vrh piramide in njena projekcija na osnovno ploskev.",
		"Ime piramide je določeno s tipom mnogokotnika, ki predstavlja osnovno ploskev.",
		"Višina piramide je razdalja vrha od ravnine osnovne ploskev piramide.",
		"Višina piramide je dolžina najkrajšega stranskega roba piramide.",
		"Piramida je pokončna, če je projekcija višine piramide na osnovno ploskev središče očrtane krožnice osnovne ploskev.",
		"Piramida je pokončna, če je en stranski rob pravokoten na ravnino osnovne ploskev.",
		"Piramida je pokončna, če se okoli njene osnovne ploskev lahko očrta krožnica.",
		"Stranski robovi pokončne piramide so med seboj enaki.",
		"Piramida je pokončna le, če je njena osnovna ploskev pravilen mnogokotnik.",
		"Plašč pokončne piramide sestavljajo izključno enakostranični trikotniki.",
		"Plašč pokončne piramide sestavljajo izključno enakokraki ali enakostranični trikotniki.",
		"Pokončna piramida je pravilna, če je njena osnova pravilni mnogokotnik.",
		"Pravilni tetraeder je telo, katerega stranice so štirje skladni enakostranični trikotniki.",
		"Glavni diagonalni presek pravilne piramide je enakokraki trikotnik, ki ga določata dve nesosednji stranski robovi in vsebuje višino.",
		"Pravilna tristranska piramida nima diagonalnega preseka.",
		"Pravilna tristranska piramida ima tri diagonalna preseka.",
		"Diagonalni presek pravilne piramide je enakokraki trikotnik.",
		"Diagonalni presek pravilne piramide je vedno enakostranični trikotnik.",
		"Piramida ima liho število robov.",
		"Topokotni trikotnik ne more biti osnovna ploskev pokončne piramide.",
		"Vsak trikotnik lahko služi kot osnovna ploskev pokončne piramide.",
		"Romb je lahko osnovna ploskev pokončne piramide.",
		"Piramida je pokončna, če so vsi njene stranski robovi enaki.",
		"Projekcija višine pokončne piramide je vedno znotraj osnovne ploskev."
		}

reply = {"n", "t", "t", "n", "n", "t", "t", "t", "n", "t", "t", "t", "t", "n", "t", "n", "н", "t", "n", "n", "t", "t", "t", "t", "t", "n", "t", "n", "n", "n", "t", "n", "t", "n"}