text = {"Pyramid is a polyhedron with two parallel congruent polygons.",
		"Pyramid is a solid whose one side is a polygon, and the other sides are triangles with a common vertex.",
        "The base of the pyramid is a polygon.",
        "The base of the pyramid is always a triangle.",
        "The envelope of the pyramid is formed by parallelograms.",
        "The envelope of the pyramid is formed by triangles.",
        "The apex of the pyramid is a common point of all lateral faces.",
        "The apex of the pyramid is a common point of all lateral edges.",
        "A tetrahedron is a four-sided pyramid.",
        "A tetrahedron is a three-sided pyramid.",
        "The height of the pyramid is the segment perpendicular to the base plane, with its ends being the apex of the pyramid and its projection on the base plane.",
        "The name of the pyramid is determined by the type of polygon that represents the base.",
        "The height of the pyramid is the distance from the apex to the base plane of the pyramid.",
        "The height of the pyramid is the length of the shortest lateral edge of the pyramid.",
        "A pyramid is right if the projection of the height of the pyramid to the base plane is the center of the circle circumscribed around the base.",
        "A pyramid is right if one lateral edge is perpendicular to the base plane.",
        "A pyramid is right if a circle can be circumscribed around its base.",
        "The lateral edges of a right pyramid are equal to each other.",
        "A pyramid is right only if its base is a regular polygon.",
        "The envelope of a right pyramid consists exclusively of equilateral triangles.",
        "The envelope of a right pyramid consists exclusively of isosceles or equilateral triangles.",
        "A right pyramid is regular if its base is a regular polygon.",
        "A regular tetrahedron is a solid whose sides are four congruent equilateral triangles.",
        "The main diagonal section of a regular pyramid is an isosceles triangle defined by two non-adjacent lateral edges and contains the height.",
        "A regular triangular pyramid does not have a diagonal section.",
        "A regular triangular pyramid has three diagonal sections.",
        "The diagonal section of a regular pyramid is an isosceles triangle.",
        "The diagonal section of a regular pyramid is always an equilateral triangle.",
        "A pyramid has an odd number of edges.",
        "An obtuse-angled triangle cannot be the base of a right pyramid.",
        "Any triangle can be the base of a right pyramid.",
        "A rhombus can be the base of a right pyramid.",
        "A pyramid is right if all its lateral edges are equal.",
        "The base of the height of the right pyramid is always inside the base."}		

reply = {"n", "t", "t", "n", "n", "t", "t", "t", "n", "t", "t", "t", "t", "n", "t", "n", "н", "t", "n", "n", "t", "t", "t", "t", "t", "n", "t", "n", "n", "n", "t", "n", "t", "n"}