
Na slici je nekoliko obojenih trouglova označenih slovima.
@center@ @mycanvas()@                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
U zadatom paru kojim preslikavanjem se jedan trougao preslikava u drugi? U prazan okvir upiši: 
 t @hspacept(8)@ ako je translacija, 
 s @hspacept(8)@ ako je centralna simetrija, 
 n @hspacept(8)@ ako nije ni jedno ni drugo.
@vspace@
@center@ @reply[1]@ @hspacept(30)@ @reply[2]@ @hspacept(30)@ @reply[3]@ 
@center@ @reply[4]@ @hspacept(30)@ @reply[5]@ @hspacept(30)@ @reply[6]@
 