
title = {"Zbir brojeva a i b.",
         "Razliku izraza 2a i 3b.",
         "Proizvod izraza 3x i y.",
		 "Proizvod izraza a + 4 i b - 4.",
         "Količnik izraza a + 2 i a - 3.",
         "Zbir kvadrata brojeva x i y.",
         "Kvadrat zbira brojeva a i b.",
         "Razliku kvadrata brojeva x i y.",
         "Kvadrat razlike brojeva a i b.",
         "Trostruki kvadrat broja x umanjen za vrednost broja x i uvećan za najveći jednocifren broj.",
         "Razliku kvadrata izraza x - 3 i broja y, podeljenu sa dvostrukim zbirom brojeva x i y.",
         "Razliku trećeg stepena broja a i izraza 2b.",
         "Količnik kvadrata broja x uvećanog za kvadrat broja a i proizvoda trostrukog broja x i broja a.",
		 "Trostruki proizvod broja x i kvadrata broja y.",
		 "Trostruki proizvod kvadrata broja x i broja y.",
		 "Trostruki proizvod kvadrata broja x i kvadrata broja y.",	
         "Količnik kvadrata razlike brojeva x i y i trećeg stepena zbira ovih brojeva.",	
		 "Trostruki kvadrat proizvoda brojeva x i y.",	
		 "Trostruki kvadrat količnika brojeva x i y.",	
		 "Trostruki količnik broja x i kvadrata broja y.",	
		 "Trostruki količnik kvadrata broja x i broja y.",	
		 "Pomoću prirodnog broja n zapiši paran broj.",		 
		 "Pomoću prirodnog broja n  zapiši negativan ceo broj.",	
		 "Pomoću prirodnog broja n zapiši broj deljiv sa p.",	
		 "Pomoću celog broja k  zapiši broj deljiv sa p sa ostatkom q.",
		 "Pomoću prirodnog broja n zapiši neparan broj."		  
		 }