title = {"Sum of numbers a and b.",
         "Difference of expressions 2a and 3b.",
         "Product of expressions 3x and y.",
         "Product of expressions a + 4 and b - 4.",
         "Quotient of expressions a + 2 and a - 3.",
         "Sum of squares of numbers x and y.",
         "Square of sum of numbers a and b.",
         "Difference of squares of numbers x and y.",
         "Square of difference of numbers a and b.",
         "Triple square of number x decreased by the value of number x and increased by the greatest one-digit number.",
         "Difference of squares of expression x - 3 and number y, divided by double sum of numbers x and y.",
         "Difference of third power of number a and expression 2b.",
         "Quotient of square of number x increased by square of number a and product of triple number x and number a.",
         "Triple product of number x and square of number y.",
         "Triple product of square of number x and number y.",
         "Triple product of square of number x and square of number y.",
         "Quotient of square of difference of numbers x and y and third power of sum of these numbers.",
         "Triple square of product of numbers x and y.",
         "Triple square of quotient of numbers x and y.",
         "Triple quotient of number x and square of number y.",
         "Triple quotient of square of number x and number y.",
         "Write an even number using a natural number n.",
         "Write a negative integer using a natural number n.",
         "Write a number divisible by p using a natural number n.",
         "Write a number divisible by p with remainder q using an integer k.",
         "Write an odd number using a natural number n."
         }