title = {"Vsota števil a in b.",
         "Razlika izrazov 2a in 3b.",
         "Produkt izraza 3x in y.",
		 "Produkt izraza a + 4 in b - 4.",
         "Količnik izrazov a + 2 in a - 3.",
         "Vsota kvadratov števil x in y.",
         "Kvadrat vsote števil a in b.",
         "Razlika kvadratov števil x in y.",
         "Kvadrat razlike števil a in b.",
         "Trojni kvadrat števila x, zmanjšan za vrednost števila x in povečan za največje enomestno število.",
         "Razlika kvadratov izraza x - 3 in števila y, deljena s dvojnim seštevkom števil x in y.",
         "Razlika tretje potence števila a in izraza 2b.",
         "Količnik kvadrata števila x povečanega za kvadrat števila a in produkta trojnega števila x in števila a.",
		 "Trojni produkt števila x in kvadrata števila y.",
		 "Trojni produkt kvadrata števila x in števila y.",
		 "Trojni produkt kvadrata števila x in kvadrata števila y.",	
         "Količnik kvadrata razlike števil x in y in tretje potence vsote teh števil.",	
		 "Trojni kvadrat produkta števil x in y.",	
		 "Trojni kvadrat količnika števil x in y.",	
		 "Trojni količnik števila x in kvadrata števila y.",	
		 "Trojni količnik kvadrata števila x in števila y.",	
		 "Zapišite s pomočjo naravnega števila n sodo število.",		 
		 "Zapišite s pomočjo naravnega števila n negativno celo število.",	
		 "Zapišite s pomočjo naravnega števila n število, ki je deljivo s p.",	
		 "Zapišite s pomočjo celog števila k število, ki je deljivo s p z ostankom q.",
		 "Zapišite s pomočjo naravnega števila n liho število."		  
		 }