msg1 = "Obseg kvadrata je "
msg2 = ". Kakšna je njegova površina?"
msg3 = "Obseg pravokotnika je "
msg4 = ". Eno od njegovih stranic je "
msg5 = " krat krajša od druge. Kakšna je površina pravokotnika?"