text = {"Through a given point we can construct only one line.",
        "Through a given point we can construct only two lines.",
        "Through a given point we can construct infinitely many lines.",
        "Through two different points we can construct two lines.",
        "Through two different points we can construct only one line.",
        "Through two different points we cannot construct any line.",
        "Two parallel lines have only one common point.",
        "Two parallel lines do not have any common points.",
        "Two parallel lines have infinitely many common points.",
        "Two different intersecting lines have only one common point.",
        "Two different intersecting lines have two common points.",
        "Two different intersecting lines do not have any common points.",
        "Two different intersecting lines have infinitely many common points.",
        "Three collinear points determine exactly one line.",
        "Three collinear points determine exactly two lines.",
        "Three collinear points determine exactly three lines.",
        "Three non-collinear points determine exactly one line.",
        "Three non-collinear points determine exactly two lines.",
        "Three non-collinear points determine exactly three lines.",
        "In a plane through a point outside a given line, we can construct only one line that does not intersect the given line.",
        "In a plane through a point outside a given line, we can construct at least two lines that do not intersect the given line.",
        "In a plane through a point outside a given line, we cannot construct any line that does not intersect the given line.",
        "In a plane through a point, we can construct only one line that is perpendicular to the given line.",
        "In a plane through a point, we can construct only two lines that are perpendicular to the given line.",
        "In a plane through a point, we can construct more than two lines that are perpendicular to the given line.",
        "Two different points on a line determine two half-lines.",
        "Two different points on a line determine three half-lines.",
        "Two different points on a line determine four half-lines.",
        "If for three different points A, B, and C it holds that AB + BC = AC, the points are collinear.",
        "If for three different points A, B, and C it holds that AB + BC = AC, the points are non-collinear.",
        "Two points not belonging to the line are on the same side of the line if the segment whose endpoints are those points intersects the line."}

reply = {"n", "n", "t", "n", "t", "n", "n", "t", "n", "t", "n", "n", "n", "t", "n", "n", "n", "t", "n", "t", "n", "n", "t", "n", "n", "n", "n", "t", "t", "n", "n"}