text = {"Skozi dano točko lahko konstruiramo le eno premico.",
        "Skozi dano točko lahko konstruiramo le dve premici.",
        "Skozi dano točko lahko konstruiramo neskončno mnogo premic.",
        "Skozi dve različne točke lahko konstruiramo dve premici.",
        "Skozi dve različne točke lahko konstruiramo le eno premico.",
        "Skozi dve različne točke ne moremo konstruirati nobene premice.",
        "Dve vzporedni premici imata le eno skupno točko.",
        "Dve vzporedni premici nimata nobene skupne točke.",
        "Dve vzporedni premici imata neskončno mnogo skupnih točk.",
        "Dve različni premici, ki se sekata, imata le eno skupno točko.",
        "Dve različni premici, ki se sekata, imata dve skupni točki.",
        "Dve različni premici, ki se sekata, nimata skupnih točk.",
        "Dve različni premici, ki se sekata, imata neskončno mnogo skupnih točk.",
        "Tri kolinearne točke določajo natanko eno premico.",
        "Tri kolinearne točke določajo natanko dve premici.",
        "Tri kolinearne točke določajo natanko tri premice.",
        "Tri nekolinearne točke določajo natanko eno premico.",
        "Tri nekolinearne točke določajo natanko dve premici.",
        "Tri nekolinearne točke določajo natanko tri premice.",
        "V ravnini skozi točko izven dane premice lahko konstruiramo le eno premico, ki ne seka dane premice.",
        "V ravnini skozi točko izven dane premice lahko konstruiramo vsaj dve premici, ki ne sekata dane premice.",
        "V ravnini skozi točko izven dane premice ne moremo konstruirati nobene premice, ki ne seka dane premice.",
        "V ravnini skozi točko lahko konstruiramo le eno premico, ki je pravokotna na dano premico.",
        "V ravnini skozi točko lahko konstruiramo le dve premici, ki sta pravokotni na dano premico.",
        "V ravnini skozi točko lahko konstruiramo več kot dve premici, ki so pravokotne na dano premico.",
        "Dve različni točki na premici določata dve poltrakovi.",
        "Dve različni točki na premici določata tri poltrakovi.",
        "Dve različni točki na premici določata štiri poltrakovi.",
        "Če za tri različne točke A, B in C velja, da je AB+BC=AC, so točke kolinearne.",
        "Če za tri različne točke A, B in C velja, da je AB+BC=AC, so točke nekolinearne.",
        "Dve točki, ki ne pripadata premici, sta na isti strani premice, če daljica, katere krajišči sta ti točki, seka premico."}

reply = {"n", "n", "t", "n", "t", "n", "n", "t", "n", "t", "n", "n", "n", "t", "n", "n", "n", "t", "n", "t", "n", "n", "t", "n", "n", "n", "n", "t", "t", "n", "n"}