
text = {"Kroz datu tačku možemo konstruisati samo jednu pravu.", 
        "Kroz datu tačku možemo konstruisati samo dve prave.",	 
        "Kroz datu tačku možemo konstruisati beskonačno mnogo pravih.",   
		"Kroz dve različite tačke možemo konstruisati dve prave.", 
        "Kroz dve različite tačke možemo konstruisati samo jednu pravu.",	 
        "Kroz dve različite tačke ne možemo konstruisati ni jednu pravu.",    
        "Dve paralelne prave imaju samo jednu zajedničku tačku.", 
        "Dve paralelne prave nemaju ni jednu zajedničku tačku.",
        "Dve paralelne prave imaju beskonačno mnogo zajedničkih tačaka.",
        "Dve različite prave koje se seku imaju samo jednu zajedničku tačku.", 	 
        "Dve različite prave koje se seku imaju dve zajedničke tačke.",
        "Dve različite prave koje se seku nemaju zajedničkih tačaka.",
        "Dve različite prave koje se seku imaju beskonačno mnogo zajedničkih tačaka.",		 
		"Tri kolinearne tačke određuju tačno jednu pravu.",
		"Tri kolinearne tačke određuju tačno dve prave.",
		"Tri kolinearne tačke određuju tačno tri prave.",
		"Tri nekolinearne tačke određuju tačno jednu pravu.",
		"Tri nekolinearne tačke određuju tačno dve prave.",
		"Tri nekolinearne tačke određuju tačno tri prave.",
		"U ravni kroz tačku van date prave možemo konstruisati samo jednu pravu koja ne seče datu pravu.",	
		"U ravni kroz tačku van date prave možemo konstruisati bar dve prave koje ne seku datu pravu.",			 
		"U ravni kroz tačku van date prave ne možemo konstruisati ni jednu pravu koja ne seče datu pravu.",		
	    "U ravni kroz tačku možemo konstruisati samo jednu pravu koja je normalna na datu pravu.",
	    "U ravni kroz tačku možemo konstruisati samo dve prave koje su normalne na datu pravu.",	
	    "U ravni kroz tačku možemo konstruisati više od dve prave koje su normalne na datu pravu.",	
		"Dve različite tačke na pravoj određuju dve poluprave.", 	
		"Dve različite tačke na pravoj određuju tri poluprave.", 			 
		"Dve različite tačke na pravoj određuju četiri poluprave.", 
		"Ako za tri različite tačke A, B i C važi da je AB+BC=AC tačke su kolinerane.",
		"Ako za tri različite tačke A, B i C važi da je AB+BC=AC tačke su nekolinerane.",
	    "Dve tačke koje ne pripadaju pravoj su sa iste strane prave ako duž čiji su krajevi te tačke seče pravu."}		 
		

reply = {"n", "n", "t", "n", "t", "n", "n", "t", "n", "t", "n", "n", "n", "t", "n", "n", "n", "t", "n", "t", "n", "n", "t", "n", "n", "n", "n", "t", "t", "n", "n" }
