text = {"A line is normal to a plane if it is normal to every line in the plane that passes through the point of penetration.",
	 "A line is normal to a plane if it is normal to at least two lines in the plane passing through the point of penetration.",
	 "A line is normal to a plane if it is normal to one line in the plane passing through the point of penetration.",
	 "The base is the point of penetration of the line normal to the plane.",
	 "There are at least two lines normal to the plane at a given point in the plane.",
	 "If two different lines are normal to the same plane, then they are parallel to each other.",
	 "If two different lines are normal to the same plane, then they are mutually normal.",
	 "If two different lines are normal to the same plane, then they are skew.",
	 "If a line is normal to a plane, a line parallel to it is normal to the plane.",
	 "If a line is normal to a plane, a line parallel to it is parallel to the plane.",
	 "Through a point outside a plane, there is only one line normal to that plane.",
	 "Through a point outside a plane, there are at least two lines normal to a given plane.",
	 "The distance from a point to a plane is the segment of the normal line from a given point to the plane.",
	 "There is a point in the plane whose distance to a given point outside the plane is less than the distance of the given point from the plane.",
	 "Two lines that are not parallel can be normal to the same plane.",
	 "Two sides of a triangle can be normal to the same plane.",
	 "Two sides of a trapezoid can be normal to the same plane.",
	 "Two sides of a rhombus can be normal to the same plane.",
	 "Through a point outside a plane there is only one line parallel to that plane.",
	 "Through a point outside a plane there are infinitely many lines parallel to that plane.",
	 "The distance between two skew lines is the length of the segment of their common normal.",
	 "The distances of the points of one plane from its parallel plane are equal.",
	 "The distances of the points of one plane from its parallel plane are not equal.",
	 "The plane α is normal to the plane β (and vice versa) if some line of the plane α and all lines parallel to it in α are normal to the plane β.",
	 "The plane α is normal to the plane β (and vice versa) if some line of the plane α and all lines parallel to it in α are normal to the line of intersection of the two planes.",
	 "If a line is normal to a given plane, then every plane containing that line is also normal to the given plane.",
	 "If a line is normal to a given plane, then there is exactly one plane that contains that line and is normal to the given plane.",
	 "If two planes are normal to the same line, then they are parallel to each other.",
	 "Two planes normal to the same line do not have to be parallel to each other.",
	 "If two planes are normal to each other and a line is parallel to the first plane, that line is always normal to the second plane.",
	 "The projection of a given point onto a plane is the base of the line normal to the plane containing the given point.",
	 "The projection of a point onto a plane is the point of penetration through the plane of any line containing that point.",
	 "The projection of a segment is determined by the projections of its endpoints.",
	 "The lengths of the segment and its projection are always equal.",
	 "The segment's projection length is not greater than the segment's length.",
	 "If the segment is parallel to the plane, the length of segment's projection is equal to the segment length.",
	 "The projection of a segment can be a point in a plane.",
	 "The orthogonal projection of a point onto a plane is the point in the plane closest to the given point.",
	 "Orthogonal projections of two skew lines always intersect.",
	 "Two parallel lines in a plane can be orthogonal projections of two parallel or two skew lines."}

reply = {"t", "t", "n", "t", "n", "t", "n", "n", "t", "n", "t", "n", "t", "n", "n", "n", "t", "t", "n", "t", "t", "t", "n", "t", "n", "t", "n", "t", "n", "n", "t", "n", "t", "n", "t", "t", "t", "t", "n", "t"}