text = {"Prava je normalna na ravan ako je normalna na svaku pravu u ravni koja prolazi kroz tačku prodora.", 
        "Prava je normalna na ravan ako je normalna bar na dve prave u ravni koje prolaze kroz tačku prodora.",	 
        "Prava je normalna na ravan ako je normalna na jednu pravu u ravni koja prolazi kroz tačku prodora.",   
		"Podnožje je tačka prodora prave normalne na ravan.", 
        "Postoje bar dve prave koje su normalne na ravan u datoj tački ravni.",	 
		"Ako su dve različite prave normalne na istu ravan, onda su one međusobno paralelne.",    
        "Ako su dve različite prave normalne na istu ravan, onda su one međusobno normalne.", 
        "Ako su dve različite prave normalne na istu ravan, onda su one međusobno mimoilazne.",
        "Ako je prava normalna na ravan, njoj paralelna prava je  normalna na ravan.",
        "Ako je prava normalna na ravan, njoj paralelna prava je  paralelna sa ravni.", 	 
        "Kroz tačku van ravni postoji samo jedna prava normalna na tu ravan.",
        "Kroz tačku van ravni postoje bar dve prave normalne na tu ravan.",
        "Rastojanje od tačke do ravni je odsečak normale iz date tačke na ravan.",
		"Postoji tačka u ravni koja je bliža datoj tački van ravni od rastojanja date tačke od ravni.",
		"Dve prave koje nisu paralelne mogu biti normalne na istu ravan.",
		"Dve stranice trougla mogu biti normalne na istu ravan.",
        "Dve stranice trapeza mogu biti normalne na istu ravan.",
		"Dve stranice romba mogu biti normalne na istu ravan.",
        "Kroz tačku van ravni postoji samo jedna prava paralelna sa tom ravni.",
        "Kroz tačku van ravni postoji beskonačno mnogo pravih paralelnih sa tom ravni.",
		"Rastojanje dve mimoilazne prave je dužina odsečka njihove zajedničke normale.",	
		"Rastojanja tačaka jedne ravni od njoj paralelne ravni su jednaka.",
		"Rastojanja tačaka jedne ravni od njoj paralelne ravni nisu jednaka.",
	    "Ravan α je normalna na ravan β (i obrnuto) ako su neka prava ravni α i sve njoj paralelne prave u α normalne na ravan β.",
	    "Ravan α je normalna na ravan β (i obrnuto) ako su neka prava ravni α i sve njoj paralelne prave u α normalne na presečnu pravu dveju ravni.",
		"Ako je neka prava normalna na datu ravan, onda je i svaka ravan koja sadrži tu pravu normalna na datu ravan.",		
	    "Ako je neka prava normalna na datu ravan, onda postoji tačno jedna ravan koja sadrži tu pravu i normalna je na datu ravan.",
		"Ako su dve ravni normalne na istu pravu onda su one paralelne među sobom.",
        "Dve ravni normalne na istu pravu ne moraju biti paralelne među sobom.",
		"Ako su dve ravni normalne jedna na drugu i prava је paralelna prvoj ravni, ta prava je uvek normalna na drugu ravan.",		
		"Projekcija tačke na ravan je podnožje prave normalne na ravan koja sadrži datu tačku.",
		"Projekcija tačke na ravan je tačka prodora kroz ravan bilo koje prave koja sadrži tu tačku.",
		"Projekcija duži je određena projekcijama njenih krajnjih tačaka.",
		"Dužine duži i njene projekcije su uvek jednake.",
		"Dužina projekcije duži nije veća od dužine duži.",
		"Ako je duž paralelna sa ravni dužina projekcije duži je jednaka sa dužinom duži.",	
		"Projekcija duži može biti tačka u ravni.",	
		"Ortogonalna projekcija tačke na ravan je tačka u ravni najbliža toj tački.",		
		"Ortogonalne projekcije  dve mimoilazne prave se uvek seku.",
		"Dve paralelne prave u ravni mogu biti ortogonalne projekcije  dve paralelne ili dve mimoilazne prave."}		

reply = {"t", "t", "n", "t", "n", "t", "n", "n", "t", "n", "t", "n", "t", "n", "n", "n", "t", "t", "n", "t", "t", "t", "n", "t", "n", "t", "n", "t", "n", "n", "t", "n", "t", "n", "t", "t", "t", "t", "n", "t"}