text = {"A line is normal to a plane if it is normal to every line in the plane passing through the point of intersection.",
        "A line is normal to a plane if it is normal to at least two lines in the plane passing through the point of intersection.",
        "A line is normal to a plane if it is normal to one line in the plane passing through the point of intersection.",
        "The foot is the point of intersection of a line normal to a plane.",
        "There are at least two lines that are normal to a plane at a given point in the plane.",
        "If two different lines are normal to the same plane, then they are parallel to each other.",
        "If two different lines are normal to the same plane, then they are normal to each other.",
        "If two different lines are normal to the same plane, then they are skew to each other.",
        "If a line is normal to a plane, then a line parallel to it is normal to the plane.",
        "If a line is normal to a plane, then a line parallel to it is parallel to the plane.",
        "Through a given point, there is only one line normal to the given plane.",
        "Through a given point, there are at least two lines normal to the given plane.",
        "The distance from a point to a plane is the segment of the normal from the given point to the plane.",
        "There is a point in the plane that is closer to the given point outside the plane than the distance of the given point from the plane.",
        "Two non-parallel lines can be normal to the same plane.",
        "Two sides of a triangle can be normal to the same plane.",
        "Two sides of a trapezoid can be normal to the same plane.",
        "Two sides of a rhombus can be normal to the same plane.",
        "Through a given point outside a given plane, there is only one line parallel to that plane.",
        "Through a given point outside a given plane, there are infinitely many lines parallel to that plane.",
        "The shortest distance between two skew lines is the segment of their common normal.",
        "The distances of points in one plane from a plane parallel to it are equal.",
        "The distances of points in one plane from a plane parallel to it are not equal.",
        "Plane α is normal to plane β (and vice versa) if some line of plane α and all lines parallel to it in α are normal to plane β.",
        "Plane α is normal to plane β (and vice versa) if some line of plane α and all lines parallel to it in α are normal to the line of intersection of the two planes.",
        "If a line is normal to a given plane, then every plane containing that line is normal to the given plane.",
        "If a line is normal to a given plane, then there is exactly one plane containing that line that is normal to the given plane.",
        "If two planes are normal to the same line, then they are parallel to each other.",
        "Two planes normal to the same line do not have to be parallel to each other.",
        "If two planes are normal to each other and a line is parallel to the first plane, then that line is always normal to the second plane.",
        "The projection of a given point onto a plane is the foot of the line normal to the plane containing the given point.",
        "The projection of a point onto a plane is the point of intersection through the plane of any line containing that point.",
        "The projection of a line is determined by the projections of its endpoints.",
        "The projection of a line is always equal to the length of the line.",
        "The projection of a line is not greater than the length of the line.",
        "If a line is parallel to a plane, the projection of the line onto the plane is equal to the length of the line.",
        "The projection of a line can be a point in the plane.",
        "The orthogonal projection of a point onto a plane is the point in the plane closest to the given point.",
        "The orthogonal projections of two skew lines always intersect.",
        "Two parallel lines in a plane can have orthogonal projections of two parallel lines or two skew lines."}

reply = {"t", "t", "n", "t", "n", "t", "n", "n", "t", "n", "t", "n", "t", "n", "n", "n", "t", "t", "n", "t", "t", "t", "n", "t", "n", "t", "n", "t", "n", "n", "t", "n", "t", "n", "t", "t", "t", "t", "n", "t"}