text = {"Premica je pravokotna na ravnino, če je pravokotna na vsako premico v ravnini, ki poteka skozi točko preboja.",
	 "Premica je pravokotna na ravnino, če je pravokotna na vsaj dve premici v ravnini, ki potekata skozi točko preboja.",
	 "Premica je pravokotna na ravnino, če je pravokotna na eno premico v ravnini, ki poteka skozi točko preboja.",
	 "Osnovica je točka preboja premice pravokotne na ravnino.",
	 "Obstajata vsaj dve premici, ki sta pravokotne na ravnino v dani točki na ravnini.",
	 "Če sta dve različni premici pravokotne na isto ravnino, med seboj sta vzporedne.",
	 "Če sta dve različni premici pravokotne na isto ravnino, med seboj sta pravokotne.",
	 "Če sta dve različni premici pravokotne na isto ravnino, med seboj sta mimoidoče.",
	 "Če je premica pravokotna na ravnino, je tudi premica, ki je vzporedna z njo, pravokotna na ravnino.",
	 "Če je premica pravokotna na ravnino, je premica, ki je vzporedna z njo, vzporedna z ravnino.", 
	 "Skozi točko zunaj ravnine poteka le ena premica pravokotna  na to ravnino.",
	 "Skozi točko zunaj ravnine potekata vsaj dve premici pravokotni na to ravnino.",
	 "Razdalja od točke do ravnine je dolžina daljice na pravokotnici od dane točke do ravnine.",
	 "Obstaja točka v ravnini, katere je oddaljenost do dane točke zunaj ravnine manjša od razdalje dane točke od ravnine.",
	 "Dve premici, ki nista vzporedni, sta lahko pravokotne na isto ravnino.",
	 "Dve stranici trikotnika sta lahko pravokotni na isto ravnino.",
	 "Dve stranici trapeza sta lahko pravokotni na isto ravnino.",
	 "Dve stranici romba sta lahko pravokotni na isto ravnino.",
	 "Skozi točko zunaj ravnine poteka samo ena premica, ki je vzporedna z to ravnino.",
	 "Skozi točko zunaj ravnine obstaja neskončno veliko premic, vzporednih s to ravnino.",
	 "Razdalja med dvema mimoidočim premicama je dolžina daljice njune skupne pravokotnice.",
	 "Razdalje točk na ravnini od ravnine, ki je vzporedna z njo, so enake.",
	 "Razdalje točk na ravnini od ravnine, ki je vzporedna z njo, niso enake.",
	 "Ravnina α je pravokotna na ravnino β (in obratno), če so nekatera premica v ravnini α in vse z njo vzporedne premice v α pravokotne na ravnino β.",
	 "Ravnina α je pravokotna na ravnino β (in obratno), če so nekatera premica v ravnini α in vse z njo vzporedne premice v α pravokotne na presečišče dveh ravnin.",
	 "Če je premica pravokotna na dano ravnino, potem je tudi vsaka ravnina, ki vsebuje to premico, normalna na dano ravnino.",
	 "Če je premica pravokotna na dano ravnino, potem obstaja točno ena ravnina, ki vsebuje to premico in je normalna na dano ravnino.",
	 "Če sta dve ravnini pravokotni na isto premico, sta med seboj vzporedni.",
	 "Ni nujno, da sta ravnini, pravokotni na isto premico, med seboj vzporedni.",
	 "Če sta dve ravnini pravokotni druga na drugo in je premica vzporedna s prvo ravnino, je ta premica vedno pravokotna na drugo ravnino.",
	 "Projekcija dane točke na ravnino je točka preboja premice pravokotne na ravnino, ki vsebuje dano točko.",
	 "Projekcija točke na ravnino je točka preboja katere koli premice, ki vsebuje to točko.",
	 "Projekcija daljice je določena s projekcijami njenih končnih točk.",
	 "Dolžine daljice in njene projekcije so vedno enake.",
	 "Dolžina projekcije daljice ni večja od dolžine daljice.",
	 "Če je daljica vzporedna z ravnino, je dolžina projekcije daljice enaka dolžini daljice.",
	 "Projekcija daljice je lahko točka v ravnini.",
	 "Pravokotna projekcija točke na ravnino je točka v ravnini, ki je najbližja dani točki.",
	 "Pravokotne projekcije dveh mimoidočih premic se vedno sekata.",
	 "Dve vzporedni premici v ravnini sta lahko pravokotni projekciji dveh vzporednih ali dveh mimoidočih premic."}		

reply = {"t", "t", "n", "t", "n", "t", "n", "n", "t", "n", "t", "n", "t", "n", "n", "n", "t", "t", "n", "t", "t", "t", "n", "t", "n", "t", "n", "t", "n", "n", "t", "n", "t", "n", "t", "t", "t", "t", "n", "t"}