text = {"Prava je normalna na ravan če je normalna na vsako pravo v ravnini, ki gre skozi točko preseka.", 
        "Prava je normalna na ravan če je normalna vsaj na dve pravi v ravnini, ki gresta skozi točko preseka.",	 
        "Prava je normalna na ravan če je normalna na eno pravo v ravnini, ki gre skozi točko preseka.",   
		"Podnožje je točka preseka prave normalne na ravan.", 
        "Obstajata vsaj dve pravi, ki sta normalni na ravan v dani točki ravnine.",	 
		"Če sta dve različni pravi normalni na isto ravnino, sta med seboj vzporedni.",    
        "Če sta dve različni pravi normalni na isto ravnino, sta med seboj normalni.", 
        "Če sta dve različni pravi normalni na isto ravnino, sta med seboj sečiščni.",
        "Če je prava normalna na ravan, ji vzporedna prava je normalna na ravan.",
        "Če je prava normalna na ravan, ji vzporedna prava je vzporedna s ravnino.", 	 
        "Skozi dano točko obstaja samo ena prava normalna na dano ravnino.",
        "Skozi dano točko obstajata vsaj dve pravi normalni na dano ravnino.",
        "Razdalja od točke do ravnine je odsek normale iz dane točke na ravnino.",
		"Obstaja točka v ravnini, ki je bližje dani točki zunaj ravnine od razdalje dane točke do ravnine.",
		"Dve pravi, ki nista vzporedni, lahko sta normalni na isto ravnino.",
		"Dve stranici trikotnika lahko sta normalni na isto ravnino.",
        "Dve stranici trapeza lahko sta normalni na isto ravnino.",
		"Dve stranici romba lahko sta normalni na isto ravnino.",
        "Skozi dano točko zunaj dane ravnine obstaja samo ena prava vzporedna s to ravnino.",
        "Skozi dano točko zunaj dane ravnine obstaja neskončno mnogo pravih vzporednih s to ravnino.",
		"Najkrajša razdalja dveh sečiščnih pravih je odsek njune skupne normale.",	
		"Razdalje točk ene ravnine do njej vzporedne ravnine so enake.",
		"Razdalje točk ene ravnine do njej vzporedne ravnine niso enake.",
	    "Ravnina α je normalna na ravnino β (in obratno), če sta neki pravi ravnine α in vse njej vzporedne prave v α normalne na ravnino β.",
	    "Ravnina α je normalna na ravnino β (in obratno), če sta neki pravi ravnine α in vse njej vzporedne prave v α normalne na presečno pravo dveh ravnin.",
		"Če je neka prava normalna na dano ravnino, je tudi vsaka ravnina, ki vsebuje to pravo, normalna na dano ravnino.",		
	    "Če je neka prava normalna na dano ravnino, obstaja natanko ena ravnina, ki vsebuje to pravo in je normalna na dano ravnino.",
		"Če sta dve ravnini normalni na eno pravo, sta med seboj vzporedni.",
        "Dve ravnini normalni na eno pravo ne morata biti vzporedni med seboj.",
		"Če sta dve ravnini normalni ena na drugo in prava vzporedna prvi ravnini, je ta prava vedno normalna na drugo ravnino.",		
		"Projekcija dane točke na ravnino je podnožje prave normalne na ravnino, ki vsebuje dano točko.",
		"Projekcija točke na ravnino je točka preseka skozi ravnino katerekoli prave, ki vsebuje to točko.",
		"Projekcija daljice je določena z projekcijami njenih krajiščnih točk.",
		"Projekcija daljice je vedno enaka daljici.",
		"Projekcija daljice ni večja od daljice.",
		"Če je daljica vzporedna s ravnino, je projekcija daljice enaka daljici.",	
		"Projekcija daljice lahko je točka v ravnini.",	
		"Ortogonalna projekcija točke na ravnino je točka v ravnini najbližja dani točki.",		
		"Ortogonalne projekcije dveh sečiščnih pravih se vedno sekata.",
		"Dve vzporedni pravi v ravnini lahko sta ortogonalni projekciji dveh vzporednih ali dveh sečiščnih pravih."}		

reply = {"t", "t", "n", "t", "n", "t", "n", "n", "t", "n", "t", "n", "t", "n", "n", "n", "t", "t", "n", "t", "t", "t", "n", "t", "n", "t", "n", "t", "n", "n", "t", "n", "t", "n", "t", "t", "t", "t", "n", "t"}