text = {"A cylinder is a rounded body.",
		"A cylinder is a horned body.", 		
		"A circular cylindrical surface is described by a line that rotates around a line parallel to it.", 
        "A cylindrical surface is a plane.", 		
        "An axis is a line containing the centers of the circles of the cylindrical surface.", 
        "The generatrix is a line containing the centers of the circles of the cylindrical surface.",   		
        "The generatrix is a line parallel to the axis of the cylindrical surface.", 
        "The generatrix and the axis of the cylindrical surface are skew lines.", 		
        "The generatrix and the axis of the cylindrical surface are mutually perpendicular lines.", 		
        "The generatrix is a line that describes the cylindrical surface by its rotating around the axis.",		
        "A cylinder is a body bounded by part of a cylindrical surface and two circles perpendicular to the axis of that surface.",		
        "The cylinder's envelope is a rectangle.",		
        "The cylinder's envelope is a part of the cylindrical surface.",		
        "The bases of the cylinder are two congruent polygons.",
        "The bases of the cylinder are two congruent circles.",		
		"The axis of the cylinder is a segment of the axis of the cylindrical surface.",		
		"The axis of the cylinder is a segment of the generatrix of the cylindrical surface.",		
		"The axis of the cylinder is a segment whose ends are the centers of the circles of the cylinder's bases.",			
		"The height of the cylinder is a line whose ends are the centers of the circles of the cylinder's base.",		
		"The parallel cross-section of the cylinder is a circle congruent with the base.",		
 		"The parallel cross-section of the cylinder is a rectangle.",
		"The perpendicular cross-section of a cylinder is a circle congruent to the base.",		
 		"The perpendicular cross-section of the cylinder is a rectangle.",		
		"The axial cross-section of the cylinder is the perpendicular cross-section containing the axis.",		
		"The cylinder is equilateral if its axial cross-section is a square.",			
	    "The height of an equilateral cylinder is equal to the diameter of the base.",
	    "The height of an equilateral cylinder is equal to the radius of the base.",			
	    "The cylinder is formed by rotating a rectangle around one side.", 
		"An equilateral cylinder is formed by rotating a square around one side."}		

reply = {"t", "n", "t", "n", "t", "n", "t", "n", "n", "t", "t", "n", "t", "n", "t", "t", "n", "t", "t", "t", "n", "n", "t", "t", "t", "t", "n", "t", "n"}