text = {"Valj je zaobljeno telo.",
		"Valj je rogljasto telo.", 		
		"Krožno valjasto površje opisuje premica, ki rotira okoli nje paralelne premice.", 
        "Valjasto površje je ravnina.", 		
        "Osa je premica, ki vsebuje centre krogov valjaste površine.", 
        "Izvodnica je premica, ki vsebuje centre krogov valjaste površine.",   		
        "Izvodnica je premica, ki je vzporedna osi valjaste površine.", 
        "Izvodnica in os valjaste površine sta sečiščni premici.", 		
        "Izvodnica in os valjaste površine sta medsebojno pravokotni premici.", 		
        "Izvodnica je premica, ki s svojim vrtenjem okoli osi opisuje valjasto površje.",		
        "Valj ali cilinder je telo, omejeno delom valjaste površine in s dvema krogoma pravokotnima na os te površine.",		
        "Ovojnica valjka je pravokotnik.",		
        "Ovojnica valjka je del valjaste površine.",		
        "Osnove ali baze valjka sta dva enaka mnogokotnika.",
        "Osnove ali baze valjka sta dva enaka kroga.",		
		"Osa valjka je odsek osi valjaste površine.",		
		"Osa valjka je odsek izvodnice valjaste površine.",		
		"Osa valjka je daljica, katere kraji so centri krogov osnove valjka.",			
		"Višina valjka je daljica, katere kraji so centri krogov osnove valjka.",		
		"Paralelni prerez valjka je krog, ki se ujema z osnovo.",		
 		"Paralelni prerez valjka je pravokotnik.",
		"Normalni prerez valjka je krog, ki se ujema z osnovo.",		
 		"Normalni prerez valjka je pravokotnik.",		
		"Osni prerez valjka je normalni prerez, ki vsebuje os.",		
		"Valj je pravokotni, če je njegov osni presek kvadrat.",			
	    "Višina pravokotnega valjka je enaka premeru osnove.",
	    "Višina pravokotnega valjka je enaka polmeru osnove.",			
	    "Valj nastane z vrtenjem pravokotnika okoli ene stranice.", 
		"Pravokotni valj nastane z vrtenjem kvadrata okoli ene stranice."}		

reply = {"t", "n", "t", "n", "t", "n", "t", "n", "n", "t", "t", "n", "t", "n", "t", "t", "n", "t", "t", "t", "n", "n", "t", "t", "t", "t", "n", "t", "n"}