text = {"Cylinder is a curved body.",
		"Cylinder is a horned body.", 		
		"A straight line that rotates around it describes a circular cylindrical surface.", 
        "The cylindrical surface is flat.", 		
        "The axis is a straight line containing the centers of the circles of the cylindrical surface.", 
        "The generatrix is a straight line containing the centers of the circles of the cylindrical surface.",   		
        "The generatrix is a straight line parallel to the axis of the cylindrical surface.", 
        "The generatrix and the axis of the cylindrical surface are skew lines.", 		
        "The generatrix and the axis of the cylindrical surface are mutually perpendicular lines.", 		
        "The generatrix is a straight line that, by rotating around the axis, describes a cylindrical surface.",		
        "A cylinder or a cylinder is a body bounded by a portion of a cylindrical surface and two circles perpendicular to the axis of that surface.",		
        "The cylinder's envelope is a rectangle.",		
        "The cylinder's envelope is a part of the cylindrical surface.",		
        "The bases of the cylinder are two congruent polygons.",
        "The bases of the cylinder are two congruent circles.",		
		"The axis of the cylinder is a segment of the axis of the cylindrical surface.",		
		"The axis of the cylinder is a segment of the generatrix of the cylindrical surface.",		
		"The axis of the cylinder is a line whose ends are the centers of the circles of the cylinder's base.",			
		"The height of the cylinder is a line whose ends are the centers of the circles of the cylinder's base.",		
		"The parallel section of the cylinder is a circle congruent to the base.",		
 		"The parallel section of the cylinder is a rectangle.",
		"The normal section of the cylinder is a circle congruent to the base.",		
 		"The normal section of the cylinder is a rectangle.",		
		"The axial section of the cylinder is a normal section containing the axis.",		
		"The cylinder is right-angled if its axial section is a square.",			
	    "The height of a right-angled cylinder is equal to the diameter of the base.",
	    "The height of a right-angled cylinder is equal to the radius of the base.",			
	    "The cylinder is formed by rotating a rectangle around one side.", 
		"A right-angled cylinder is formed by rotating a square around one side."}		

reply = {"t", "n", "t", "n", "t", "n", "t", "n", "n", "t", "t", "n", "t", "n", "t", "t", "n", "t", "t", "t", "n", "n", "t", "t", "t", "t", "n", "t", "n"}