text = {"Valj je okroglo telo.",
		"Valj je rogasto telo.", 		
		"Krožna valjasta ploskev je opisana s premico, ki se vrti okoli nje vzporedne premice.", 
        "Valjasta ploskev je ravnina.", 		
        "Osa je premica, ki vsebuje središča krogov valjaste ploskve.", 
        "Izvodnica je premica, ki vsebuje središča krogov valjaste ploskve.",   		
        "Izvodnica je premica, ki je vzporedna osi valjaste ploskve.", 
        "Izvodnica in os valjaste ploskve sta mimoidoči premici.", 		
        "Izvodnica in os valjaste ploskve sta medsebojno pravokotni premici.", 		
        "Izvodnica je premica, ki z vrtenjem okoli osi opisuje valjasto ploskev.",		
        "Valj je telo, ki je omejeno z delom valjaste ploskve in z dvema krogoma, ki sta normalni na os te ploskve.",		
        "Plašč valjka je pravokotnik.",		
        "Plašč valjka je del valjaste ploskve.",		
        "Osnovne ploskve valja sta dva skladna mnogokotnika.",
        "Osnovne ploskve valja sta dva skladna kroga.",		
		"Os valja je odsek osi valjaste ploskve.",		
		"Os valja je odsek izvodnice valjaste ploskve.",		
		"Os valja je daljica, katere kraji so središča krogov osnovnih ploskev valja.",			
		"Višina valja je daljica, katere kraji so središča krogov osnovnih ploskev valja.",		
		"Vzporedni presek valja je krog, ki je skladen z osnovno ploskev.",		
 		"Vzporedni presek valja je pravokotnik.",
		"Pravokotni presek valja je krog, ki je skladen z osnovno ploskev.",		
 		"Pravokotni presek valja je pravokotnik.",		
		"Osni prerez valja je pravokotni presek, ki vsebuje os.",		
		"Valj je enakostranični, če je njegov osni presek kvadrat.",			
	    "Višina enakostraničnega valja je enaka premeru osnove.",
	    "Višina enakostraničnega valja je enaka polmeru osnove.",			
	    "Valj nastane z vrtenjem pravokotnika okoli ene stranice.", 
	    "Enakostranični valj nastane z vrtenjem kvadrata okoli ene stranice."}		

reply = {"t", "n", "t", "n", "t", "n", "t", "n", "n", "t", "t", "n", "t", "n", "t", "t", "n", "t", "t", "t", "n", "n", "t", "t", "t", "t", "n", "t", "n"}