
text = {"Valjak je oblo telo.",
		"Valjak je rogljasto telo.", 		
		"Kružnu cilindričnu površ opisuje prava koja rotira oko njoj paralelne prave.", 
        "Cilindrična površ je ravan.", 		
        "Osa je prava koja sadrži centre krugova cilindrične površi.", 
        "Izvodnica je prava koja sadrži centre krugova cilindrične površi.",   		
        "Izvodnica je prava paralelna osi cilindrične površi.", 
        "Izvodnica i osa cilindrične površi su mimoilazne prave.", 		
        "Izvodnica i osa cilindrične površi su uzajamno normalne prave.", 		
        "Izvodnica je prava koja svojim obrtanjem oko ose opisuje cilindričnu površ.",		
        "Valjak ili cilindar je telo ograničeno delom cilindrične površi i sa dva kruga normalna na osu te površi.",		
        "Omotač valjka je pravougaonik.",		
        "Omotač valjka je deo cilindrične površi.",		
        "Osnove ili baze valjka su dva  podudarna mnogougla.",
        "Osnove ili baze valjka su dva podudarna kruga.",		
		"Osa valjka je odsečak ose cilindrične površi.",		
		"Osa valjka je odsečak izvodnice cilindrične površi.",		
		"Osa valjka je duž čiji su krajevi centri krugova osnova valjka.",			
		"Visina valjka je duž čiji su krajevi centri krugova osnove valjka.",		
		"Paraleni presek valjka je krug podudaran osnovi.",		
 		"Paraleni presek valjka je pravougaonik.",
		"Normalni presek valjka je krug podudaran osnovi.",		
 		"Normalni presek valjka je pravougaonik.",		
		"Osni presek valjka je normalni presek koji sadrži osu.",		
		"Valjak je ravnostrani ako mu je osni presek kvadrat.",			
	    "Visina ravnostranog valjka jednaka je prečniku osnove.",
	    "Visina ravnostranog valjka jednaka je poluprečniku osnove.",			
	    "Valjak nastaje obrtanjem pravougaonika oko jedne stranice.", 
		"Ravnostrani valjak nastaje obrtanjem kvadrata oko jedne stranice."}		

reply = {"t", "n", "t", "n", "t", "n", "t", "n", "n", "t", "t", "n", "t", "n", "t", "t", "n", "t", "t", "t", "n", "n", "t", "t", "t", "t", "n", "t", "n"}
