text = {"Prism is a polyhedron with two parallel congruent polygons.",
		"Prism is a polyhedron with two parallel congruent quadrilaterals.",
        "The lateral faces of a prism are always rectangles.",   		 
        "The lateral faces of a prism are parallelograms.", 
        "The lateral faces of a prism form the prism's lateral surface.",   
        "The lateral faces of a prism form the prism's base.", 
        "Congruent polygons form the prism's lateral surface.",   
        "Parallel congruent polygons form the prism's base.", 		
        "The lateral edges of every prism are perpendicular to the base plane.",
        "The lateral edges of a right prism are perpendicular to the base plane.",
        "The lateral faces of a right prism are rectangles.",		
        "The name of a prism is determined by the type of polygon that represents the base.",		
        "A parallelepiped is any right quadrilateral prism.",
        "A parallelepiped is a right quadrilateral prism with a parallelogram base.",
		"A cuboid is a right rectangular parallelepiped.",
		"The height of a prism is the length of its lateral edge.",
		"The height of a prism is the distance between the parallel bases.",		
		"The height of a right prism is the length of its lateral edge.",		
		"The diagonal of a cuboid is the line segment whose endpoints are the vertices of the two bases and does not belong to the lateral surface.",
 		"The diagonal of a cuboid is the diagonal of its base.",
  		"The diagonal of a cuboid is the diagonal of its lateral face.",		
  		"The diagonal section of a cuboid is a rectangle determined by two parallel diagonals of the bases.",		
		"A cube is a right quadrilateral prism with equal edges.",
		"A cube is a regular polyhedron.",		
	    "A triangular prism has no diagonals.",
	    "A triangular prism has three diagonals.",		
	    "A cuboid has two diagonals.", 
"A cuboid has four diagonals."}		

reply = {"t", "n", "n", "t", "t", "n", "n", "t", "n", "t", "t", "t", "n", "t", "t", "n", "t", "t", "t", "n", "n", "t", "t", "t", "t", "n", "n", "t"}