text = {"Prizma je polieder z dvema vzporednima skladnima mnogokotnikoma.",
		"Prizma je polieder, ki ima dva vzporedna skladna štirikotnika.",
		"Stranske ploskve prizme so vedno pravokotniki.",
		"Stranske ploskve prizme so paralelogrami.",
		"Stranske ploskve prizme tvorijo plašč prizme.",
		"Stranske ploskve prizme tvorijo osnovo prizme.",
		"Skladni mnogokotniki tvorijo plašč prizme.",
		"Vzporedni skladni mnogokotniki tvorijo osnovo prizme.",
		"Stranski robovi vsake prizme so pravokotni na ravnino osnovne ploskev.",
		"Stranski robovi pokončne prizme so pravokotni na ravnino osnovne ploskev.",
		"Stranske ploskve pokončne prizme so pravokotniki.",
		"Ime prizme določa vrsta poligona, ki predstavlja osnovno ploskev.",
		"Paralelepiped je vsaka pravilna štiristranska prizma.",
		"Paralelepiped je pokončna štiristranska prizma, katere osnovna ploskev je paralelogram.",
		"Kvader je pokončen paralelepiped.",
		"Višina prizme je dolžina njenega stranskega roba.",
		"Višina prizme je razdalja med vzporednima osnovnima ploskvima.",
		"Višina pokončne prizme je dolžina njenega stranskega roba.",
		"Telesna diagonala kvadra je daljica, katere konci so oglišči obeh osnovih ploskev in ki ne pripada plašču.",
		"Telesna diagonala kvadra je diagonala njegove osnovne ploskev.",
		"Telesna diagonala kvadra je diagonala njegove stranske ploskev.",  
		"Diagonalni presek kvadra je pravokotnik, določen z dvema vzporednima diagonalama osnovnih ploskev.",		
		"Kocka je pokončna štiristranska prizma z enakimi robovi.",
		"Kocka je pravilen polieder.",		
		"Tristranska prizma nima diagonal.",
		"Tristranska prizma ima tri diagonale.",
	    "Kvader ima dve telesne dijagonale.",		
		"Kvader ima štiri telesne diagonale."}		

reply = {"t", "n", "n", "t", "t", "n", "n", "t", "n", "t", "t", "t", "n", "t", "t", "n", "t", "t", "t", "n", "n", "t", "t", "t", "t", "n", "n", "t"}