
text = {"Prizma je poliedar sa dva paralelna podudarna mnogougla.", 
		"Prizma je poliedar sa dva paralelna podudarna četvorougla.", 
        "Bočne strane prizme su uvek pravougaonici.",   		 
        "Bočne strane prizme su paralelogrami.", 
        "Bočne strane prizme obrazuju omotač prizme.",   
        "Bočne strane prizme obrazuju osnovu prizme.", 
        "Podudarni mnogouglovi obrazuju omotač prizme.",   
        "Paralelni podudarni mnogouglovi obrazuju osnovu prizme.", 		
        "Bočne ivice svake prizme su normalne na ravan osnove.",
        "Bočne ivice prave prizme su normalne na ravan osnove.",
        "Bočne strane prave prizme su pravougaonici.",		
        "Naziv prizme određen je vrstom mnogougla koji predstavlja osnovu.",		
        "Paralelepiped je bilo koja prava četvorostrana prizma.",
        "Paralelepiped je prava četvorostrana prizma čija je osnova paralelogram.",
		"Kvadar je pravougli paralelepiped.",
		"Visina prizme je dužina njene bočne ivice.",
		"Visina prizme je rastojanje između paralelnih osnova.",		
		"Visina prave prizme je dužina njene bočne ivice.",		
		"Dijagonala kvadra je duž čiji su krajevi temena dveju osnova, a koja ne pripada omotaču.",
 		"Dijagonala kvadra je dijagonala njegove osnove.",
  		"Dijagonala kvadra je dijagonala njegove bočne strane.",		
  		"Dijagonalni presek kvadra je pravougaonik određen dvema paralelnim dijagonalama osnova.",		
		"Kocka je prava četvorostrana prizma jednakih ivica.",
		"Kocka je pravilni poliedar.",		
	    "Trostrana prizma nema dijagonala.",
	    "Trostrana prizma ima tri dijagonale.",		
	    "Kvadar ima dve dijagonale.", 
"Kvadar ima četiri dijagonale."}		

reply = {"t", "n", "n", "t", "t", "n", "n", "t", "n", "t", "t", "t", "n", "t", "t", "n", "t", "t", "t", "n", "n", "t", "t", "t", "t", "n", "n", "t"}
