text = {"A prism is a polyhedron with two parallel congruent polygons.",
		"A prism is a polyhedron that has two parallel congruent quadrilaterals.",
        "The lateral faces of a prism are always rectangles.",   		 
        "The lateral faces of a prism are parallelograms.", 
        "The lateral faces of the prism form the envelope of the prism.",   
        "The lateral faces of the prism form the base of the prism", 
        "Congruent polygons form the envelope of a prism.",   
        "Parallel congruent polygons form the base of a prism.", 		
        "The lateral edges of every prism are perpendicular to the base plane.",
        "The lateral edges of a right prism are perpendicular to the base plane.",
        "The lateral faces of a right prism are rectangles.",		
        "The name of a prism is determined by the type of polygon that represents the base.",		
        "A parallelepiped is any right quadrilateral prism.",
        "A parallelepiped is a right quadrilateral prism with a parallelogram base.",
		"A cuboid is a right rectangular parallelepiped.",
		"The height of a prism is the length of its lateral edge.",
		"The height of a prism is the distance between the parallel bases.",		
		"The height of a right prism is the length of its lateral edge.",		
		"The diagonal of a cuboid is the segment whose endpoints are the vertices of the two bases and does not belong to the envelope.",
 		"The diagonal of a cuboid is the diagonal of its base.",		
  		"The diagonal of a cuboid is the diagonal of its lateral face.",		
  		"The diagonal section of a cuboid is a rectangle determined by two parallel diagonals of the bases.",		
		"A cube is a right quadrilateral prism with equal edges.",
		"A cube is a regular polyhedron.",		
	    "A triangular prism has no diagonals.",
	    "A triangular prism has three diagonals.",		
	    "A cuboid has two diagonals.", 
		"A cuboid has four diagonals."}		

reply = {"t", "n", "n", "t", "t", "n", "n", "t", "n", "t", "t", "t", "n", "t", "t", "n", "t", "t", "t", "n", "n", "t", "t", "t", "t", "n", "n", "t"}