text = {"Prizma je poliedar s tremi vzporednimi enakokraki mnogokotniki.", 
		"Prizma je poliedar s tremi vzporednimi enakokraki štirikotniki.", 
        "Stranice prizme so vedno pravokotniki.",   		 
        "Stranice prizme so paralelogrami.", 
        "Stranice prizme tvorijo ovojnico prizme.",   
        "Stranice prizme tvorijo osnovo prizme.", 
        "Enakokraki mnogokotniki tvorijo ovojnico prizme.",   
        "Vzporedni enakokraki mnogokotniki tvorijo osnovo prizme.", 		
        "Stranice vsake prizme so pravokotne na ravnino osnove.",
        "Stranice prave prizme so pravokotniki.",
        "Stranice prave prizme so pravokotniki.",		
        "Ime prizme je določeno z vrsto mnogokotnika, ki predstavlja osnovo.",		
        "Paralelepiped je katerikoli pravi štiristrani poliedar.",
        "Paralelepiped je prava štiristrana prizma, katere osnova je paralelogram.",
		"Kvader je pravokotni paralelepiped.",
		"Višina prizme je dolžina njene stranice.",
		"Višina prizme je razdalja med vzporednima osnovama.",		
		"Višina prave prizme je dolžina njene stranice.",		
		"Diagonala kvadra je daljica, katere kraji so vrhovi dveh osnov, ki pa ne spadata v ovojnico.",
 		"Diagonala kvadra je diagonala njegove osnove.",
  		"Diagonala kvadra je diagonala njegove stranice.",		
  		"Diagonalni prerez kvadra je pravokotnik, določen z dvema vzporednima diagonalama osnov.",		
		"Kocka je prava štiristrana prizma z enakimi robovi.",
		"Kocka je pravilni polieder.",		
	    "Triangulna prizma nima diagonal.",
	    "Triangulna prizma ima tri diagonale.",		
	    "Kvader ima dve diagonali.", 
"Kvader ima štiri diagonale."}		

reply = {"t", "n", "n", "t", "t", "n", "n", "t", "n", "t", "t", "t", "n", "t", "t", "n", "t", "t", "t", "n", "n", "t", "t", "t", "t", "n", "n", "t"}