text = {"Dve točki določata ravnino.", 
        "Tri kolinearne točke določajo ravnino.",	 
        "Tri nekolinearne točke določajo ravnino.",   
		"Prava leži v ravnini če ena točka prave leži v ravnini.", 
        "Prava leži v ravnini če dve različni točki prave ležita v ravnini.",	 
		"Prava seka ravnino če samo ena točka prave leži v ravnini.",    
        "Prava seka ravnino če dve različni točki prave ležita v ravnini.", 
        "Prava je vzporedna z ravnino če vsaj ena točka prave leži v ravnini.",
        "Prava je vzporedna z ravnino če nima skupnih točk z ravnino.",
        "Ne seka se prave pripadajo isti ravnini.", 	 
        "Ne seka se prave ne pripadajo isti ravnini.",
        "Ne seka se prave nimajo skupnih točk.",
        "Ne seka se prave imajo eno skupno točko.",
		"Dve prave ki se sekata določata ravnino.",
		"Dve vzporedni pravi določata ravnino.",
		"Dve ne seka se pravi določata ravnino.",
        "Prava je vzporedna z ravnino če je vzporedna s pravo ki pripada ravnini.",
		"Ena prava določa ravnino.",
		"Ena prava in točka izven prave določata ravnino.",
		"Dve ravnini se sekata če imata samo eno skupno pravo.",	
		"Dve ravnini se sekata če imata dve različiti skupni pravi.",	
		"Dve ravnini se prekrivata če imata tri skupne nekolinearne točke.",
		"Dve ravnini sta vzporedni če je ena prava prve ravnine vzporedna s katero koli pravo druge ravnine.",
	    "Dve ravnini sta vzporedni če nimata skupnih točk.",
	    "Dve ravnini sta ne seka se če nimata skupnih točk.",	
		"Če dve ravnini imata eno skupno točko, potem imata vsaj še eno skupno točko.",		
	    "Dve točki ki ne pripadajo ravnini sta na isti strani ravnine če daljica kateri pripadata ti točki nima skupnih točk z ravnino."}		 
		

reply = {"n", "n", "t", "n", "t", "t", "n", "n", "t", "n", "t", "t", "n", "t", "t", "n", "t", "n", "t", "t", "n", "t", "n", "t", "n", "t", "t" }