text = {"Two points determine a plane.",
        "Three collinear points determine a plane.",
        "Three non-collinear points determine a plane.",
        "A line lies in a plane if one point of the line lies in the plane.",
        "A line lies in a plane if two different points of the line lie in the plane.",
        "A line intersects a plane if only one point of the line lies in the plane.",
        "A line intersects a plane if two different points of the line lie in the plane.",
        "A line is parallel to a plane if at least one point of the line lies in the plane.",
        "A line is parallel to a plane if it has no common points with the plane.",
        "Skew lines belong to the same plane.",
        "Skew lines do not belong to the same plane.",
        "Skew lines have no common points.",
        "Skew lines have one common point.",
        "Two intersecting lines determine a plane.",
        "Two parallel lines determine a plane.",
        "Two skew lines determine a plane.",
        "A line is parallel to a plane if it is parallel to a line that belongs to the plane.",
        "One line determines a plane.",
        "One line and a point outside the line determine a plane.",
        "Two planes intersect if they have only one common line.",
        "Two planes intersect if they have two different common lines.",
        "Two planes coincide if they have three common non-collinear points.",
        "Two planes are parallel if a line of the first plane is parallel to a line of the second plane.",
        "Two planes are parallel if they have no common points.",
        "Two planes are skew if they have no common points.",
        "If two planes have one common point, then they have at least one more common point.",
        "Two points not belonging to a plane are on the same side of the plane if the segment whose endpoints are those points has no common points with the plane."}

reply = {"n", "n", "t", "n", "t", "t", "n", "n", "t", "n", "t", "t", "n", "t", "t", "n", "t", "n", "t", "t", "n", "t", "n", "t", "n", "t", "t"}