text = {"Dve točki določata ravnino.", 
        "Tri kolinearne točke določajo ravnino.",	 
        "Tri nekolinearne točke določajo ravnino.",   
		"Premica leži v ravnini če ena točka premice leži v ravnini.", 
        "Premica leži v ravnini če dve različni točki premice ležita v ravnini.",	 
		"Premica seka ravnino če samo ena točka premice leži v ravnini.",    
        "Premica seka ravnino če dve različni točki premice ležita v ravnini.", 
        "Premica je vzporedna z ravnino če vsaj ena točka premice leži v ravnini.",
        "Premica je vzporedna z ravnino če nima skupnih točk z ravnino.",
        "Mimoidoče premice pripadajo isti ravnini.", 	 
        "Mimoidoče premice ne pripadajo isti ravnini.",
        "Mimoidoče premice nimajo skupnih točk.",
        "Mimoidoče premice imajo eno skupno točko.",
		"Dve premice ki se sekata določata ravnino.",
		"Dve vzporedne premice določata ravnino.",
		"Dve mimoidoče premice določata ravnino.",
        "Premica je vzporedna z ravnino če je vzporedna s premico ki pripada ravnini.",
		"Ena premica določa ravnino.",
		"Ena premica in točka izven premice določata ravnino.",
		"Dve ravnini se sekata če imata samo eno skupno premico.",	
		"Dve ravnini se sekata če imata dve različiti skupni premici.",	
		"Dve ravnini se prekrivata če imata tri skupne nekolinearne točke.",
		"Dve ravnini sta vzporedni če je ena premica prve ravnine vzporedna s katero koli premico druge ravnine.",
	    "Dve ravnini sta vzporedni če nimata skupnih točk.",
	    "Dve ravnini sta mimoidoče če nimata skupnih točk.",	
		"Če dve ravnini imata eno skupno točko, potem imata vsaj še eno skupno točko.",		
	    "Dve točki ki ne pripadajo ravnini sta na isti strani ravnine če daljica kateri pripadata ti točki nima skupnih točk z ravnino."}		 
		

reply = {"n", "n", "t", "n", "t", "t", "n", "n", "t", "n", "t", "t", "n", "t", "t", "n", "t", "n", "t", "t", "n", "t", "n", "t", "n", "t", "t" }