msg_1 = "Za koliko bi se spremenila površina škatle, če bi vse dimenzije škatle"
msg_2 = " povečali za "
msg_3 = " Površina bi se povečala za "
msg_4 = " zmanjšale za "
msg_5 = " Površina bi se zmanjšala za "

msg_6 = "Kolikokrat bi se spremenila površina škatle, če bi vse dimenzije škatle"
msg_7 = " povečali "
msg_8 = " -krat?"
msg_9 = " Površina bi se povečala "
msg_10 = "-krat."
msg_11 = " zmanjšali "
msg_12 = " Površina bi se zmanjšala "
