msg1 = "Površina kvadrata je "
msg2 = ". Koliki je njegov obim?"
msg3 = "Površina pravougaonika je "
msg4 = ". Jedna njegova stranica je "
msg5 = " puta kraća od druge. Koliki je obim pravougaonika?"
