msg1 = "Ploščina kvadrata je "
msg2 = ". Kolikšen je njegov obseg?"
msg3 = "Ploščina pravokotnika je "
msg4 = ". Ena njegova stranica je "
msg5 = " - krat krajša od druge. Kolikšen je obseg pravokotnika?"