ones = {"nič", "ena", "dva", "tri", "štiri", "pet", "šest", "sedem", "osem", "devet"}
ones2 = {"nic", "ena", "dva", "tri", "stiri", "pet", "sest", "sedem", "osem", "devet"}
tens = {"deset", "dvajset", "trideset", "štirideset", "petdeset", "šestdeset", "sedemdeset", "osemdeset", "devetdeset"}
tens2 = {"deset", "dvajset", "trideset", "stirideset", "petdeset", "sestdeset", "sedemdeset", "osemdeset", "devetdeset"}
hundreds = {"sto", "dvesto", "tristo", "štiristo", "petsto", "šeststo", "sedemsto", "osemsto", "devetsto"}
hundreds2 = {"sto", "dvesto", "tristo", "stiristo", "petsto", "seststo", "sedemsto", "osemsto", "devetsto"}
mid = {"deset", "enajst", "dvanajst", "trinajst", "štirinajst", "petnajst", "šestnajst", "sedemnajst", "osemnajst", "devetnajst"}
mid2 = {"deset", "enajst", "dvanajst", "trinajst", "stirinajst", "petnajst", "sestnajst", "sedemnajst", "osemnajst", "devetnajst"}
lang = 2